Repository net-daemon/netdaemon, pull requests merged in 2021-06, with the labels that each got.

#385 Fix two corner-case bugs handling state
  src/Daemon/NetDaemon.Daemon/Daemon/NetDaemonHost.cs
Labels: pr: bugfix

#389 Bump HassClient Version
  src/App/NetDaemon.App/NetDaemon.App.csproj
  src/Daemon/NetDaemon.Daemon/NetDaemon.Daemon.csproj
  src/DaemonRunner/DaemonRunner/DaemonRunner.csproj
Labels: pr: dependency-update

#390 Devcontainer: Always latest focal release dotnet 5 git + tools
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: pr: enhancement

#395 Fix: switch on or off NetDeamon apps with array does not work
  src/Daemon/NetDaemon.Daemon/Daemon/NetDaemonHost.cs
Labels: pr: enhancement

#397 add yaml multilevel mapping
  src/Daemon/NetDaemon.Daemon/Daemon/Config/YamlAppConfig.cs
  tests/NetDaemon.Daemon.Tests/DaemonRunner/Config/ConfigTest.cs
  tests/NetDaemon.Daemon.Tests/DaemonRunner/Config/MultilevelMappingConfig.cs
Labels: pr: new-feature

#396 add enum support to yaml
  src/Daemon/NetDaemon.Daemon/Daemon/Config/YamlExtensions.cs
  tests/NetDaemon.Daemon.Tests/DaemonRunner/Config/ConfigTest.cs
  tests/NetDaemon.Daemon.Tests/DaemonRunner/Config/EnumTest.cs
Labels: pr: new-feature

#394 Handle HassClient HassState.State is now a string
  src/App/NetDaemon.App/NetDaemon.App.csproj
  src/Daemon/NetDaemon.Daemon/Daemon/EntityStateManagement.cs
  src/Daemon/NetDaemon.Daemon/Daemon/ExtendedHassState.cs
  src/Daemon/NetDaemon.Daemon/Daemon/NetDaemonHost.cs
  src/Daemon/NetDaemon.Daemon/Mapping/EntityStateMapper.cs
  src/Daemon/NetDaemon.Daemon/NetDaemon.Daemon.csproj
  src/DaemonRunner/DaemonRunner/DaemonRunner.csproj
  src/Fakes/NetDaemon.Fakes/DaemonHostTestBase.cs
  src/Fakes/NetDaemon.Fakes/HassClientMock.cs
  tests/NetDaemon.Daemon.Tests/Daemon/NetDaemonHostTests.cs
  tests/NetDaemon.Daemon.Tests/FakesTests/FakeTests.cs
Labels: pr: enhancement
