Repository net-daemon/netdaemon, pull requests merged in 2021-12, with the labels that each got.

#537 When releasing, remove publish PR automatically
  .github/workflows/tags_docker.yml
Labels: pr: bugfix

#539 Draft NumericSensors
  src/HassModel/NetDaemon.HassModel.CodeGenerator/EntitySet.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Generator.Entitites.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/NamingHelper.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/CodeGeneratorTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Entities/EntityExtensionsTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Entities/EntityTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Entities/EnumerableEntityExtensionsTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Entities/NumericEntityTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/AppScopedHaContextProviderTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/EntityStateCacheTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/HassModel/NetDaemon.HassModel.Tests/TestHelpers/HaContextMock.cs
  src/HassModel/NetDaemon.HassModel.Tests/TestHelpers/TestEntity.cs
  src/HassModel/NetDeamon.HassModel/Entities/Entity.cs
  src/HassModel/NetDeamon.HassModel/Entities/EntityExtensions.cs
  src/HassModel/NetDeamon.HassModel/Entities/EntityState.cs
  src/HassModel/NetDeamon.HassModel/Entities/NumericEntity.cs
  src/HassModel/NetDeamon.HassModel/Entities/NumericEntityState.cs
  src/HassModel/NetDeamon.HassModel/Entities/StateChange.cs
Labels: pr: enhancement

#541 Add xml comments to the generated code based on HA matadata
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Generator.Entitites.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Generator.ExtensionMethods.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Generator.Services.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/HassServiceArgumentMapper.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/SyntaxFactoryHelper.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/ServiceArguments.cs
Labels: pr: new-feature

#542 Hass model areas
  src/Daemon/NetDaemon.Daemon/Daemon/NetDaemonHost.cs
  src/DevelopmentApps/apps/M3Test/M3App.cs
  src/HassModel/NetDaemon.HassModel.Tests/Entities/EntityTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/EntityAreaCacheTests.cs
  src/HassModel/NetDeamon.HassModel/Common/IHaContext.cs
  src/HassModel/NetDeamon.HassModel/DependencyInjectionSetup.cs
  src/HassModel/NetDeamon.HassModel/Entities/Area.cs
  src/HassModel/NetDeamon.HassModel/Entities/Entity.cs
  src/HassModel/NetDeamon.HassModel/Internal/AppScopedHaContextProvider.cs
  src/HassModel/NetDeamon.HassModel/Internal/EntityAreaCache.cs
  src/HassModel/NetDeamon.HassModel/Internal/HassObjectMapper.cs
  tests/NetDaemon.Daemon.Tests/Daemon/NetDaemonHostTests.cs
Labels: pr: new-feature

#543 Use the generated class instead of anonymous type when calling servic…
  src/HassModel/NetDaemon.HassModel.CodeGenerator/ServiceArguments.cs
Labels: pr: bugfix

#545 Register Services from Dynamic compiled code
  src/App/NetDaemon.App/Common/ServiceCollectionExtensionAttribute.cs
  src/DaemonRunner/DaemonRunner/NetDaemonExtensions.cs
  src/DaemonRunner/DaemonRunner/Service/App/DaemonAppCompiler.cs
  src/DaemonRunner/DaemonRunner/Service/App/DaemonCompiler.cs
  tests/NetDaemon.Daemon.Tests/DaemonRunner/App/DaemonAppTests.cs
  tests/NetDaemon.Daemon.Tests/DaemonRunner/Fixtures/AppWithDiSetup/RequireServiceApp.cs
  tests/NetDaemon.Daemon.Tests/NetDaemon.Daemon.Tests.csproj
Labels: pr: enhancement

#547 New HassModel.Integration project with RegisterServiceCallBack
  NetDaemon.sln
  src/DevelopmentApps/NetDaemon.DevelopmentApps.csproj
  src/DevelopmentApps/apps/HassModel/HelloModel/HelloHassModel.cs
  src/HassModel/NetDaemon.HassModel.Integration/IntegrationHaContextExtensions.cs
  src/HassModel/NetDaemon.HassModel.Integration/NetDaemon.HassModel.Integration.csproj
  src/HassModel/NetDaemon.HassModel.Tests/Integration/IntegrationHaContextExtensionsTests.cs
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/HassModel/NetDaemon.HassModel.Tests/TestHelpers/HaContextMock.cs
Labels: pr: new-feature

#551 making constructors public to enable external unit testing
  src/HassModel/NetDeamon.HassModel/Entities/StateChange.cs
Labels: pr: enhancement

#552 remove New HassClient from HassModel
  src/HassModel/NetDeamon.HassModel/NetDaemon.HassModel.csproj
Labels: pr: bugfix

#553 Add SendEvent to HassModel
  src/DevelopmentApps/apps/HassModel/HelloModel/HelloHassModel.cs
  src/HassModel/NetDeamon.HassModel/Common/IHaContext.cs
  src/HassModel/NetDeamon.HassModel/Internal/AppScopedHaContextProvider.cs
Labels: pr: new-feature

#554 fix incorrect JsonPropertyName for service parameter records
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Generator.Services.cs
Labels: pr: bugfix

#555 Add hass model interation component to nuget
  .github/workflows/push_nuget_manual.yml
  .github/workflows/tags_nuget.yml
Labels: pr: bugfix

#558 Fix bug with missing reference to scheduler
  src/DaemonRunner/DaemonRunner/DaemonRunner.csproj
  src/DaemonRunner/DaemonRunner/Service/App/DaemonCompiler.cs
Labels: pr: bugfix

#564 Fix #561 NumericEntity used current culture instead of invariant culture to parse State
  src/HassModel/NetDaemon.HassModel.Tests/Entities/NumericEntityTest.cs
  src/HassModel/NetDeamon.HassModel/Entities/NumericEntity.cs
  src/HassModel/NetDeamon.HassModel/Entities/NumericEntityState.cs
  src/HassModel/NetDeamon.HassModel/Internal/FormatHelpers.cs
Labels: pr: bugfix

#559 Fix NumberEntity generated as NumericNumberEntity
  src/HassModel/NetDaemon.HassModel.CodeGenerator/EntitySet.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Generator.Entitites.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/EntityIdHelper.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/CodeGeneratorTest.cs
Labels: pr: bugfix
