Repository net-daemon/netdaemon, pull requests merged in 2021-01, with the labels that each got.

#272 Fixes syntax and added EntityState property on gen
  src/App/NetDaemon.App/Common/Reactive/ObservableExtensionMethods.cs
  src/DaemonRunner/DaemonRunner/Service/App/CodeGenerator.cs
  src/Fakes/NetDaemon.Fakes/RxAppMock.cs
  tests/NetDaemon.Daemon.Tests/DaemonRunner/CodeGen/CodeGenTestFixture.cs
  tests/NetDaemon.Daemon.Tests/SchedulerTests.cs
Labels: pr: new-feature

#276 New integration and async fix
  src/App/NetDaemon.App/Common/INetDaemon.cs
  src/App/NetDaemon.App/Common/Reactive/INetDaemonReactive.cs
  src/App/NetDaemon.App/Common/Reactive/NetDaemonRxApp.cs
  src/App/NetDaemon.App/NetDaemon.App.csproj
  src/Daemon/NetDaemon.Daemon/Daemon/INetDaemonHost.cs
  src/Daemon/NetDaemon.Daemon/Daemon/NetDaemonHost.cs
  src/Daemon/NetDaemon.Daemon/NetDaemon.Daemon.csproj
  src/DaemonRunner/DaemonRunner/DaemonRunner.csproj
  src/Fakes/NetDaemon.Fakes/RxAppMock.cs
  tests/NetDaemon.Daemon.Tests/Daemon/NetDaemonHostTests.cs
Labels: pr: new-feature

#281 Wait for response CallService
  src/App/NetDaemon.App/Common/INetDaemon.cs
  src/App/NetDaemon.App/Common/Reactive/INetDaemonReactive.cs
  src/App/NetDaemon.App/Common/Reactive/NetDaemonRxApp.cs
  src/App/NetDaemon.App/Common/Reactive/RxEntity.cs
  src/Daemon/NetDaemon.Daemon/Daemon/NetDaemonHost.cs
  src/DevelopmentApps/apps/DebugApp/DebugApp.cs
  src/Fakes/NetDaemon.Fakes/RxAppMock.cs
Labels: pr: new-feature

#282 Dispose bugfix
  src/App/NetDaemon.App/NetDaemon.App.csproj
  src/Daemon/NetDaemon.Daemon/NetDaemon.Daemon.csproj
  src/DaemonRunner/DaemonRunner/DaemonRunner.csproj
Labels: pr: bugfix

#285 Add missing scheduler interface to INetDaemonRxApp
  src/App/NetDaemon.App/Common/Reactive/INetDaemonReactive.cs
Labels: pr: bugfix

#286 Fix Entities in RxMock
  src/Fakes/NetDaemon.Fakes/RxAppMock.cs
  tests/NetDaemon.Daemon.Tests/FakesTests/FakeMockableApp.cs
  tests/NetDaemon.Daemon.Tests/FakesTests/RxMockTests.cs
Labels: pr: bugfix

#299 Functional RunIn Mock and Time Travel functionality
  src/Fakes/NetDaemon.Fakes/NetDaemon.Fakes.csproj
  src/Fakes/NetDaemon.Fakes/RxAppMock.cs
  tests/NetDaemon.Daemon.Tests/FakesTests/FakeMockableApp.cs
  tests/NetDaemon.Daemon.Tests/FakesTests/RxMockTests.cs
Labels: pr: new-feature

#301 fix Microsoft faulty baseimage
  Dockerfile
Labels: pr: bugfix

#302 devcontainer fix
  .devcontainer/Dockerfile
  src/Fakes/NetDaemon.Fakes/RxAppMock.cs
Labels: pr: dependency-update

#304 fix base image
  Dockerfile
Labels: pr: bugfix
