Repository net-daemon/netdaemon, pull requests merged in 2021-05, with the labels that each got.

#362 CI fixes
  .github/workflows/check_pr_label.yml
  .github/workflows/ci_build.yml
  .github/workflows/push_docker_dev.yml
  .github/workflows/tags_docker.yml
  .github/workflows/tags_nuget.yml
Labels: pr: enhancement

#360 make code generation logic injectable
  src/DaemonRunner/DaemonRunner/NetDaemonExtensions.cs
  src/DaemonRunner/DaemonRunner/Service/App/CodeGenerationHandler.cs
  src/DaemonRunner/DaemonRunner/Service/App/CodeGenerator.cs
  src/DaemonRunner/DaemonRunner/Service/App/ICodeGenerationHandler.cs
  src/DaemonRunner/DaemonRunner/Service/App/ICodeGenerator.cs
  src/DaemonRunner/DaemonRunner/Service/RunnerService.cs
Labels: pr: enhancement

#363 release drafter use pr: breaking change
  .github/release-drafter.yml
Labels: pr: enhancement

#364 push docker manual with tag
  .github/workflows/push_docker_manual.yml
Labels: pr: new-feature

#369 Added webhook support
  src/App/NetDaemon.App/Common/INetDaemon.cs
  src/App/NetDaemon.App/Common/Reactive/INetDaemonReactive.cs
  src/App/NetDaemon.App/Common/Reactive/NetDaemonRxApp.cs
  src/App/NetDaemon.App/NetDaemon.App.csproj
  src/Daemon/NetDaemon.Daemon/Daemon/Config/YamlExtensions.cs
  src/Daemon/NetDaemon.Daemon/Daemon/NetDaemonHost.cs
  src/Daemon/NetDaemon.Daemon/NetDaemon.Daemon.csproj
  src/DaemonRunner/DaemonRunner/DaemonRunner.csproj
  src/Fakes/NetDaemon.Fakes/DaemonHostTestBase.cs
  src/Fakes/NetDaemon.Fakes/HassClientMock.cs
  tests/NetDaemon.Daemon.Tests/DaemonRunner/Config/ConfigTest.cs
  tests/NetDaemon.Daemon.Tests/Reactive/RxAppTest.cs
Labels: pr: new-feature

#372 fix: stop duplicate ci runs
  .github/workflows/ci_build.yml
Labels: pr: bugfix

#370 Extracted Statemanagement from NetDaemonHost
  src/Daemon/NetDaemon.Daemon/Daemon/EntityStateManagement.cs
  src/Daemon/NetDaemon.Daemon/Daemon/NetDaemonHost.cs
  src/Fakes/NetDaemon.Fakes/DaemonHostTestBase.cs
  tests/NetDaemon.Daemon.Tests/Daemon/NetDaemonHostTests.cs
  tests/NetDaemon.Daemon.Tests/FakesTests/FakeTests.cs
  tests/NetDaemon.Daemon.Tests/Reactive/RxAppTest.cs
Labels: pr: enhancement

#371 ci: add sonar scanner to ci_build
  .github/workflows/ci_build.yml
Labels: pr: enhancement

#373 ci(sonar): analyze test results / coverage
  .github/workflows/ci_build.yml
Labels: pr: enhancement

#374 docs: add sonar quality gate to readme
  README.md
Labels: pr: enhancement

#375 Cleanup part 1
  src/App/NetDaemon.App/Common/FluentExpandoObject.cs
  src/App/NetDaemon.App/Common/IHttpHandler.cs
  src/App/NetDaemon.App/Common/NetDaemonAppBase.cs
  src/App/NetDaemon.App/Common/Reactive/Services/ClimateEntity.cs
  src/App/NetDaemon.App/Common/Reactive/Services/CoverEntity.cs
  src/App/NetDaemon.App/Common/Reactive/Services/DeviceTrackerEntity.cs
  src/App/NetDaemon.App/Common/Reactive/Services/GroupEntity.cs
  src/App/NetDaemon.App/Common/Reactive/Services/ImageProcessingEntity.cs
  src/App/NetDaemon.App/Common/Reactive/Services/InputBooleanEntity.cs
  src/App/NetDaemon.App/Common/Reactive/Services/LockEntity.cs
  src/App/NetDaemon.App/Common/Reactive/Services/MediaPlayerEntity.cs
  src/App/NetDaemon.App/Common/Reactive/Services/PersistentNotificationEntity.cs
  src/App/NetDaemon.App/Common/Reactive/Services/PersonEntity.cs
  src/App/NetDaemon.App/Common/Reactive/Services/RxEntityBase.cs
  src/App/NetDaemon.App/Common/Reactive/Services/SceneEntity.cs
  src/App/NetDaemon.App/Common/Reactive/Services/ScriptEntity.cs
  src/App/NetDaemon.App/Common/Reactive/Services/VacuumEntity.cs
  src/App/NetDaemon.App/Common/Reactive/Services/ZoneEntity.cs
  src/Daemon/NetDaemon.Daemon/Daemon/Config/YamlAppConfig.cs
  src/Daemon/NetDaemon.Daemon/Daemon/NetDaemonHost.cs
  src/DaemonRunner/DaemonRunner/Service/App/CodeGenerator.cs
  tests/NetDaemon.Daemon.Tests/Daemon/NetDaemonHostTests.cs
  tests/NetDaemon.Daemon.Tests/FakesTests/FakeTests.cs
  tests/NetDaemon.Daemon.Tests/Reactive/RxAppTest.cs
Labels: pr: enhancement

#376 Refactor state management
  src/Daemon/NetDaemon.Daemon/Daemon/EntityStateManagement.cs
  src/Daemon/NetDaemon.Daemon/Daemon/NetDaemonHost.cs
  src/Daemon/NetDaemon.Daemon/Mapping/EntityStateMapper.cs
  src/Fakes/NetDaemon.Fakes/DaemonHostTestBase.cs
  tests/NetDaemon.Daemon.Tests/Daemon/NetDaemonHostTests.cs
  tests/NetDaemon.Daemon.Tests/FakesTests/FakeTests.cs
  tests/NetDaemon.Daemon.Tests/Reactive/RxAppTest.cs
Labels: pr: enhancement

#378 Added environment protection for sonar analysis
  .github/workflows/ci_build.yml
Labels: pr: enhancement

#379 More cleanup and fixing restart bug
  src/App/NetDaemon.App/Common/ExtensionMethods.cs
  src/App/NetDaemon.App/Common/INetDaemon.cs
  src/App/NetDaemon.App/Common/Reactive/INetDaemonReactive.cs
  src/App/NetDaemon.App/Common/Reactive/NetDaemonRxApp.cs
  src/Daemon/NetDaemon.Daemon/Daemon/Config/YamlAppConfig.cs
  src/Daemon/NetDaemon.Daemon/Daemon/Config/YamlExtensions.cs
  src/Daemon/NetDaemon.Daemon/Daemon/EntityStateManagement.cs
  src/Daemon/NetDaemon.Daemon/Daemon/NetDaemonHost.cs
  src/Fakes/NetDaemon.Fakes/DaemonHostTestBase.cs
Labels: pr: enhancement

#381 Adding integration matrix integration tests to real HA instance
  .github/workflows/ci_integration_tests.yaml
  .vscode/tasks.json
  NetDaemon.sln
  scripts/run_integration_tests.sh
  src/App/NetDaemon.App/Common/Reactive/Services/AutomationEntity.cs
  src/DaemonRunner/DaemonRunner/Service/App/CodeGenerator.cs
  src/DevelopmentApps/apps/DebugApp/DebugApp.cs
  src/Fakes/NetDaemon.Fakes/HassClientMock.cs
  src/Fakes/NetDaemon.Fakes/RxAppMock.cs
  tests/Integration/HA/config/automations.yaml
  tests/Integration/HA/config/configuration.yaml
  tests/Integration/HA/config/groups.yaml
  tests/Integration/HA/config/scenes.yaml
  tests/Integration/HA/config/scripts.yaml
  tests/Integration/HA/config/secrets.yaml
  tests/Integration/HA/docker-compose.yaml
  tests/Integration/README.md
  tests/Integration/TestClient/.gitignore
  tests/Integration/TestClient/HostExtension.cs
  tests/Integration/TestClient/IntegrationTestsService.cs
  tests/Integration/TestClient/Program.cs
  tests/Integration/TestClient/TestCases.cs
  tests/Integration/TestClient/TestClient.csproj
  tests/Integration/TestClient/_appsettings.Development.json
  tests/Integration/TestClient/appsettings.json
  tests/Integration/apps/HelloWorld/HelloWorld.cs
  tests/Integration/apps/HelloWorld/HelloWorld.yaml
  tests/NetDaemon.Daemon.Tests/FakesTests/FakeTests.cs
  tests/NetDaemon.Daemon.Tests/NetDaemonApp/NetDaemonAppTests.cs
Labels: pr: enhancement

#382 Remove annoying http client informational logging
  src/DaemonRunner/DaemonRunner/Infrastructure/Config/SerilogConfigurator.cs
  src/Service/_appsettings.Development.json
  src/Service/appsettings.json
Labels: pr: enhancement

#383 Clean channels
  src/Daemon/NetDaemon.Daemon/Daemon/EntityStateManagement.cs
  src/Daemon/NetDaemon.Daemon/Daemon/NetDaemonHost.cs
  src/Daemon/NetDaemon.Daemon/Daemon/TextToSpeechService.cs
  src/Fakes/NetDaemon.Fakes/DaemonHostTestBase.cs
  tests/NetDaemon.Daemon.Tests/Daemon/NetDaemonHostTests.cs
Labels: pr: enhancement
