Repository net-daemon/netdaemon, pull requests merged in 2021-07, with the labels that each got.

#400 Fix some warnings in tesproject
  src/Fakes/NetDaemon.Fakes/DaemonHostTestBase.cs
  src/Fakes/NetDaemon.Fakes/HassClientMock.cs
Labels: pr: enhancement

#401 CI: Cleanup and move analysis on own step when pushing to dev and main
  .github/workflows/ci_analyze.yml
  .github/workflows/ci_build.yml
  src/Daemon/NetDaemon.Daemon/Daemon/EntityStateManagement.cs
  tests/NetDaemon.Daemon.Tests/DaemonRunner/Config/ConfigTest.cs
  tests/NetDaemon.Daemon.Tests/DaemonRunner/Config/MultilevelMappingConfig.cs
Labels: pr: enhancement

#402 Maintenance: Various code smell fixes
  src/App/NetDaemon.App/Common/Exceptions/Exceptions.cs
  src/App/NetDaemon.App/Common/FluentExpandoObject.cs
  src/App/NetDaemon.App/Common/INetDaemon.cs
  src/App/NetDaemon.App/Common/Messages.cs
  src/App/NetDaemon.App/Common/NetDaemonAppBase.cs
  src/App/NetDaemon.App/Common/Reactive/ObservableBase.cs
  src/Daemon/NetDaemon.Daemon/Daemon/CodeManager.cs
  src/Daemon/NetDaemon.Daemon/Daemon/Config/YamlAppConfig.cs
  src/Daemon/NetDaemon.Daemon/Daemon/Config/YamlExtensions.cs
  src/Daemon/NetDaemon.Daemon/Daemon/DaemonAppExtensions.cs
  src/Daemon/NetDaemon.Daemon/Daemon/HttpHandler.cs
  src/Daemon/NetDaemon.Daemon/Daemon/NetDaemonHost.cs
  src/Daemon/NetDaemon.Daemon/Daemon/Storage/DataRepository.cs
  src/Daemon/NetDaemon.Daemon/Infrastructure/Extensions/TaskExtensions.cs
  src/Daemon/NetDaemon.Daemon/Mapping/EntityStateMapper.cs
  src/DaemonRunner/DaemonRunner/Service/App/CodeGenerationHandler.cs
  src/DaemonRunner/DaemonRunner/Service/App/DaemonCompiler.cs
  src/DaemonRunner/DaemonRunner/Service/RunnerService.cs
  src/Fakes/NetDaemon.Fakes/HassClientMock.cs
  tests/NetDaemon.Daemon.Tests/Daemon/NetDaemonHostTests.cs
  tests/NetDaemon.Daemon.Tests/DaemonRunner/App/DaemonAppTests.cs
Labels: pr: enhancement

#410 adding climate support using integration
  src/Daemon/NetDaemon.Daemon/Daemon/EntityStateManagement.cs
Labels: pr: new-feature

#412 Implemented FocusAttribute
  src/App/NetDaemon.App/Common/FocusAttribute.cs
  src/DaemonRunner/DaemonRunner/Service/RunnerService.cs
Labels: pr: new-feature

#415 Revert state manager
  src/Daemon/NetDaemon.Daemon/Daemon/EntityStateManagement.cs
  src/Daemon/NetDaemon.Daemon/Daemon/ExtendedHassState.cs
  src/Daemon/NetDaemon.Daemon/Daemon/NetDaemonHost.cs
  src/Daemon/NetDaemon.Daemon/Mapping/EntityStateMapper.cs
  src/Fakes/NetDaemon.Fakes/DaemonHostTestBase.cs
  tests/NetDaemon.Daemon.Tests/Daemon/NetDaemonHostTests.cs
  tests/NetDaemon.Daemon.Tests/FakesTests/FakeTests.cs
  tests/NetDaemon.Daemon.Tests/Reactive/RxAppTest.cs
Labels: pr: enhancement

#416 Update EntityStateMapper.cs
  src/Daemon/NetDaemon.Daemon/Mapping/EntityStateMapper.cs
Labels: pr: bugfix

#419 Fix the area feature
  src/App/NetDaemon.App/NetDaemon.App.csproj
  src/Daemon/NetDaemon.Daemon/Daemon/EntityStateManagement.cs
  src/Daemon/NetDaemon.Daemon/Daemon/NetDaemonHost.cs
  src/Daemon/NetDaemon.Daemon/NetDaemon.Daemon.csproj
  src/DaemonRunner/DaemonRunner/DaemonRunner.csproj
  src/DevelopmentApps/apps/HelloWorld/HelloWorld.cs
  src/Fakes/NetDaemon.Fakes/HassClientMock.cs
  tests/NetDaemon.Daemon.Tests/Daemon/NetDaemonHostTests.cs
Labels: pr: bugfix, pr: enhancement

#420 Remove notification from debug apo
  src/DevelopmentApps/apps/DebugApp/DebugApp.cs
Labels: pr: enhancement
