Repository net-daemon/netdaemon, pull requests merged in 2021-09, with the labels that each got.

#452 CI_FIX
  Model3/ExtensionMethods.cs
  Model3/Model3.csproj
  Model3/ModelV3/Domains/ZoneEntity.cs
  Model3/ModelV3/Entity.cs
  Model3/ModelV3/EntityExtensions.cs
  Model3/ModelV3/EntityState.cs
  Model3/ModelV3/EventTypes/ZhaEvent.cs
  Model3/ModelV3/Internal/EntityStateCache.cs
  Model3/ModelV3/Internal/HaContextProvider.cs
  Model3/ModelV3/TypedEventProvider.cs
Labels: pr: enhancement

#453 MoveModel3Project
  NetDaemon.sln
  src/DevelopmentApps/NetDaemon.DevelopmentApps.csproj
  src/DevelopmentApps/apps/CallServiceApp.cs
  src/DevelopmentApps/apps/M3Test/M3App.cs
  src/DevelopmentApps/apps/TtsApp.cs
  src/DevelopmentApps/apps/YamlEntities/YamlEntitiesApp.cs
  src/DevelopmentApps/apps/ZhaApp.cs
  src/Model3/NetDeamon.Model3/Common/Context.cs
  src/Model3/NetDeamon.Model3/Common/IEventProvider.cs
  src/Model3/NetDeamon.Model3/Common/IHaContext.cs
  src/Model3/NetDeamon.Model3/DependencyInjectionSetup.cs
  src/Model3/NetDeamon.Model3/Domains/Climate/ClimateEntity.cs
  src/Model3/NetDeamon.Model3/Domains/Sensor/NumericSensorEntity.cs
  src/Model3/NetDeamon.Model3/Domains/Zone/ZoneEntity.cs
  src/Model3/NetDeamon.Model3/Entities/Entity.cs
  src/Model3/NetDeamon.Model3/Entities/EntityExtensions.cs
  src/Model3/NetDeamon.Model3/Entities/EntitySet.cs
  src/Model3/NetDeamon.Model3/Entities/EntityState.cs
  src/Model3/NetDeamon.Model3/Entities/StateChange.cs
  src/Model3/NetDeamon.Model3/EventTypes/ZhaEvent.cs
  src/Model3/NetDeamon.Model3/ExtensionMethods.cs
  src/Model3/NetDeamon.Model3/Internal/EntityStateCache.cs
  src/Model3/NetDeamon.Model3/Internal/HaContextProvider.cs
  src/Model3/NetDeamon.Model3/Internal/HassObjectMapperMapper.cs
  src/Model3/NetDeamon.Model3/Internal/TypedEventProvider.cs
  src/Model3/NetDeamon.Model3/NetDaemon.Model3.csproj
  src/Service/Program.cs
Labels: pr: enhancement

#454 Ci_fix_2
  .github/workflows/test_docker.yml
Labels: pr: enhancement

#451 Isolated observable
  NetDaemon.sln
  src/App/NetDaemon.App/Common/INetDaemonCommon.cs
  src/Daemon/NetDaemon.Daemon/Daemon/NetDaemonHost.cs
  src/Daemon/NetDaemon.Daemon/Infrastructure/ObservableHelpers/ObservableHelpers.cs
  src/DevelopmentApps/apps/InterfaceApp/InterfaceApp.cs
  src/DevelopmentApps/apps/Isolation.cs
  src/DevelopmentApps/apps/YamlEntities/YamlEntitiesApp.cs
  src/Model3/NetDaemon.Model3.Tests/Internal/ScopedObservableTests.cs
  src/Model3/NetDaemon.Model3.Tests/NetDaemon.Model3.Tests.csproj
  src/Model3/NetDeamon.Model3/DependencyInjectionSetup.cs
  src/Model3/NetDeamon.Model3/Internal/HaContextProvider.cs
  src/Model3/NetDeamon.Model3/Internal/ScopedObservable.cs
  src/Model3/NetDeamon.Model3/Internal/TypedEventProvider.cs
  src/Model3/NetDeamon.Model3/NetDaemon.Model3.csproj
Labels: pr: enhancement

#455 Fix_RunEveryMinute
  src/App/NetDaemon.App/Common/Reactive/NetDaemonRxApp.cs
Labels: pr: bugfix

#456 Make EntityStateCache store states once and forward events to apps
  src/Model3/NetDaemon.Model3.Tests/Internal/EntityStateCacheTest.cs
  src/Model3/NetDeamon.Model3/Internal/EntityStateCache.cs
  src/Model3/NetDeamon.Model3/Internal/HaContextProvider.cs
Labels: pr: enhancement

#457 fix camelCase confused with PascalCase
  src/Daemon/NetDaemon.Daemon/Daemon/Config/ConfigExtensions.cs
  src/Daemon/NetDaemon.Daemon/Daemon/Config/YamlExtensions.cs
  src/DaemonRunner/DaemonRunner/Service/App/CodeGenerator.cs
Labels: pr: enhancement

#459 Fix Todo's
  src/App/NetDaemon.App/Common/ApplicationContext.cs
  src/App/NetDaemon.App/Common/ApplicationMetadata.cs
  src/App/NetDaemon.App/Common/ApplicationPersistenceService.cs
  src/App/NetDaemon.App/Common/IApplicationMetadata.cs
  src/App/NetDaemon.App/Common/NetDaemonAppBase.cs
  src/Daemon/NetDaemon.Daemon/Daemon/EntityStateManagement.cs
  src/Daemon/NetDaemon.Daemon/Daemon/ITextToSpeechService.cs
  src/Daemon/NetDaemon.Daemon/DependencyInjectionSetup.cs
  src/DaemonRunner/DaemonRunner/NetDaemonExtensions.cs
  src/DevelopmentApps/apps/M3Test/M3App.cs
  src/Model3/NetDeamon.Model3/DependencyInjectionSetup.cs
  src/Model3/NetDeamon.Model3/Internal/AppScopedHaContextProvider.cs
  src/Service/Program.cs
Labels: pr: enhancement

#458 Merge dev
  src/App/NetDaemon.App/Common/Reactive/NetDaemonRxApp.cs
  src/Daemon/NetDaemon.Daemon/Daemon/Config/ConfigExtensions.cs
  src/Daemon/NetDaemon.Daemon/Daemon/Config/YamlExtensions.cs
  src/DaemonRunner/DaemonRunner/Service/App/CodeGenerator.cs
Labels: pr: enhancement

#461 Fix_connect
  src/DaemonRunner/DaemonRunner/NetDaemonExtensions.cs
  src/DevelopmentApps/apps/CallServiceApp.cs
  src/DevelopmentApps/apps/InterfaceApp/InterfaceApp.cs
Labels: pr: bugfix

#462 Integration test improvements
  .github/workflows/ci_integration_tests.yaml
  tests/Integration/HA/config/configuration.yaml
Labels: pr: enhancement

#464 Use container logs instead of log file
  .github/workflows/ci_integration_tests.yaml
Labels: pr: enhancement

#463 Integration test improvements (#462)
  .github/workflows/ci_integration_tests.yaml
  tests/Integration/HA/config/configuration.yaml
Labels: pr:merge

#465 UnitTest_Model3
  src/DevelopmentApps/apps/M3Test/M3App.cs
  src/Model3/NetDaemon.Model3.Tests/Entities/EntityTest.cs
  src/Model3/NetDaemon.Model3.Tests/Internal/AppScopedHaContextProviderTest.cs
  src/Model3/NetDaemon.Model3.Tests/Internal/EntityStateCacheTest.cs
  src/Model3/NetDaemon.Model3.Tests/NetDaemon.Model3.Tests.csproj
  src/Model3/NetDeamon.Model3/DependencyInjectionSetup.cs
  src/Model3/NetDeamon.Model3/Entities/Entity.cs
  src/Model3/NetDeamon.Model3/Entities/EntityState.cs
  src/Model3/NetDeamon.Model3/Internal/AppScopedHaContextProvider.cs
  src/Model3/NetDeamon.Model3/Internal/HassObjectMapperMapper.cs
Labels: pr: enhancement

#467 code cover support for model3
  .github/workflows/ci_build.yml
  .github/workflows/ci_build_remodel.yml
  .gitignore
  src/Model3/NetDaemon.Model3.Tests/NetDaemon.Model3.Tests.csproj
Labels: pr: enhancement

#470 Add Model3 XML comments
  src/DevelopmentApps/Domains/Climate/ClimateEntity.cs
  src/DevelopmentApps/Domains/Sensor/NumericSensorEntity.cs
  src/DevelopmentApps/Domains/Zone/ZoneEntity.cs
  src/DevelopmentApps/apps/CallServiceApp.cs
  src/DevelopmentApps/apps/DebugApp/DebugApp.cs
  src/DevelopmentApps/apps/InterfaceApp/InterfaceApp.cs
  src/DevelopmentApps/apps/M3Test/M3App.cs
  src/DevelopmentApps/apps/YamlEntities/YamlEntitiesApp.cs
  src/DevelopmentApps/apps/ZhaApp.cs
  src/Model3/NetDeamon.Model3/Common/IEventProvider.cs
  src/Model3/NetDeamon.Model3/Common/IHaContext.cs
  src/Model3/NetDeamon.Model3/DependencyInjectionSetup.cs
  src/Model3/NetDeamon.Model3/Entities/Entity.cs
  src/Model3/NetDeamon.Model3/Entities/EntityExtensions.cs
  src/Model3/NetDeamon.Model3/Entities/EntitySet.cs
  src/Model3/NetDeamon.Model3/Entities/EntityState.cs
  src/Model3/NetDeamon.Model3/Entities/StateChange.cs
  src/Model3/NetDeamon.Model3/EventTypes/ZhaEvent.cs
  src/Model3/NetDeamon.Model3/Internal/AppScopedHaContextProvider.cs
  src/Model3/NetDeamon.Model3/Internal/ExtensionMethods.cs
  src/Model3/NetDeamon.Model3/NetDaemon.Model3.csproj
Labels: pr: enhancement
