Repository net-daemon/netdaemon, pull requests merged in 2021-11, with the labels that each got.

#497 Load settings for codegen from current folder cconfig
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Program.cs
Labels: pr: enhancement

#499 fix comment typos
  src/App/NetDaemon.App/Common/Reactive/INetDaemonReactive.cs
  src/App/NetDaemon.App/Common/Reactive/RxEntity.cs
Labels: pr: bugfix

#498 Enumerable extensions
  src/HassModel/NetDaemon.HassModel.Tests/Entities/EntityTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Entities/EnumerableEntityExtensionsTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/TestHelpers/Extensions.cs
  src/HassModel/NetDaemon.HassModel.Tests/TestHelpers/TestEntity.cs
  src/HassModel/NetDeamon.HassModel/Common/IHaContext.cs
  src/HassModel/NetDeamon.HassModel/Entities/Entity.cs
  src/HassModel/NetDeamon.HassModel/Entities/EntityExtensions.cs
  src/HassModel/NetDeamon.HassModel/Entities/EnumerableEntityExtensions.cs
  src/HassModel/NetDeamon.HassModel/Entities/StateChange.cs
Labels: pr: new-feature

#501 Fix warnings in codegen
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Generator.Entitites.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Generator.Services.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/ServiceArguments.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/CodeGeneratorTest.cs
Labels: pr: enhancement

#502 Exposes the schedulers time in scheduling API
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/Scheduling/SchedulingTests.cs
  src/Extensions/NetDaemon.Extensions.Scheduling/INetDaemonScheduler.cs
  src/Extensions/NetDaemon.Extensions.Scheduling/NetDaemonScheduler.cs
Labels: pr: new-feature

#503 Publish dev images to ghcr
  .github/workflows/push_docker_dev.yml
Labels: pr: enhancement, pr: new-feature

#504 Add context name in default logging
  src/DaemonRunner/DaemonRunner/Infrastructure/Config/SerilogConfigurator.cs
Labels: pr: new-feature

#505 ServiceTarget.FromEntities support
  src/HassModel/NetDaemon.HassModel.Tests/Common/ServiceTargetTest.cs
  src/HassModel/NetDeamon.HassModel/Common/ServiceTarget.cs
Labels: pr: enhancement

#506 Adds GH container registry for release and manual release
  .github/workflows/push_docker_manual.yml
  .github/workflows/tags_docker.yml
Labels: pr: enhancement

#507 chore: update highbyte/sonarscan-dotnet to v2.1.2
  .github/workflows/ci_analyze.yml
Labels: pr: dependency-update

#516 Make sure Entity<>.Attributes return current state
  src/HassModel/NetDaemon.HassModel.Tests/Entities/EntityTest.cs
  src/HassModel/NetDeamon.HassModel/Entities/Entity.cs
Labels: pr: bugfix

#517 Made State[All]Changes() Methods iso Properties
  src/DevelopmentApps/apps/Isolation.cs
  src/DevelopmentApps/apps/M3Test/M3App.cs
  src/DevelopmentApps/apps/YamlEntities/YamlEntitiesApp.cs
  src/HassModel/NetDaemon.HassModel.Tests/Entities/EntityTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Entities/EnumerableEntityExtensionsTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/AppScopedHaContextProviderTest.cs
  src/HassModel/NetDeamon.HassModel/Common/HaContextExtensions.cs
  src/HassModel/NetDeamon.HassModel/Common/IHaContext.cs
  src/HassModel/NetDeamon.HassModel/Entities/Entity.cs
  src/HassModel/NetDeamon.HassModel/Entities/EntityExtensions.cs
  src/HassModel/NetDeamon.HassModel/Entities/EnumerableEntityExtensions.cs
  src/HassModel/NetDeamon.HassModel/Internal/AppScopedHaContextProvider.cs
Labels: pr: breaking change

#519 .net 6
  .devcontainer/Dockerfile
  .github/workflows/ci_build.yml
  .github/workflows/ci_integration_tests.yaml
  .github/workflows/push_nuget_manual.yml
  .github/workflows/release_drafter.yml
  .github/workflows/tags_nuget.yml
  .linting/roslynator.ruleset
  .vscode/launch.json
  Dockerfile
  src/App/NetDaemon.App/Common/ApplicationContexts/ApplicationContext.cs
  src/App/NetDaemon.App/Common/ApplicationPersistenceService.cs
  src/App/NetDaemon.App/Common/NetDaemonAppBase.cs
  src/App/NetDaemon.App/Common/Reactive/NetDaemonRxApp.cs
  src/App/NetDaemon.App/Common/Reactive/ObservableBase.cs
  src/App/NetDaemon.App/NetDaemon.App.csproj
  src/Daemon/NetDaemon.Daemon/Daemon/AppManager.cs
  src/Daemon/NetDaemon.Daemon/Daemon/DaemonAppExtensions.cs
  src/Daemon/NetDaemon.Daemon/Daemon/EntityStateManagement.cs
  src/Daemon/NetDaemon.Daemon/Daemon/HttpHandler.cs
  src/Daemon/NetDaemon.Daemon/Daemon/NetDaemonHost.cs
  src/Daemon/NetDaemon.Daemon/NetDaemon.Daemon.csproj
  src/DaemonRunner/DaemonRunner/DaemonRunner.csproj
  src/DaemonRunner/DaemonRunner/Service/API/WsHandler.cs
  src/DaemonRunner/DaemonRunner/Service/App/DaemonAppCompiler.cs
  src/DaemonRunner/DaemonRunner/Service/App/DaemonCompiler.cs
  src/DaemonRunner/DaemonRunner/Service/App/LocalDaemonAppCompiler.cs
  src/DaemonRunner/DaemonRunner/Service/RunnerService.cs
  src/DevelopmentApps/NetDaemon.DevelopmentApps.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/NetDaemon.Extensions.Scheduling.Tests.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling/NetDaemon.Extensions.Scheduling.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling/NetDaemonScheduler.cs
  src/Fakes/NetDaemon.Fakes/DaemonHostTestBase.cs
  src/Fakes/NetDaemon.Fakes/HassClientMock.cs
  src/Fakes/NetDaemon.Fakes/LoggerMock.cs
  src/Fakes/NetDaemon.Fakes/NetDaemon.Fakes.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Program.cs
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/HassModel/NetDeamon.HassModel/NetDaemon.HassModel.csproj
  src/Service/Program.cs
  src/Service/Service.csproj
  tests/Integration/TestClient/TestCases.cs
  tests/Integration/TestClient/TestClient.csproj
  tests/NetDaemon.Daemon.Tests/Daemon/NetDaemonHostTests.cs
  tests/NetDaemon.Daemon.Tests/DaemonRunner/Api/ApiTests.cs
  tests/NetDaemon.Daemon.Tests/DaemonRunner/App/DaemonAppTests.cs
  tests/NetDaemon.Daemon.Tests/DaemonRunner/Config/ConfigTest.cs
  tests/NetDaemon.Daemon.Tests/FakesTests/FakeTests.cs
  tests/NetDaemon.Daemon.Tests/NetDaemon.Daemon.Tests.csproj
  tests/NetDaemon.Daemon.Tests/Reactive/RxAppTest.cs
  tests/NetDaemon.Daemon.Tests/Reactive/RxSchedulers.cs
Labels: pr: enhancement, Breaking Change, pr: breaking change

#522 Generate Attribute class properties based on JsonKind of Json
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Generator.Entitites.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Generator.ExtensionMethods.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Generator.Services.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Generator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/HomeAssistantSettings.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/TypeHelper.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Program.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/ServiceArguments.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/CodeGeneratorTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/HassModel/NetDeamon.HassModel/NetDaemon.HassModel.csproj
Labels: pr: bugfix

#524 New HassClient using .NET 6
  src/App/NetDaemon.App/NetDaemon.App.csproj
  src/Daemon/NetDaemon.Daemon/NetDaemon.Daemon.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDeamon.HassModel/NetDaemon.HassModel.csproj
Labels: pr: dependency-update

#525 Log correct app type on startup
  src/Daemon/NetDaemon.Daemon/Daemon/AppManager.cs
Labels: pr: enhancement

#529 Fix scheduling lifetime
  src/Extensions/NetDaemon.Extensions.Scheduling/DependencyInjectionSetup.cs
Labels: pr: bugfix

#530 Fix StateAllChanges to use scoped state subscription
  src/HassModel/NetDeamon.HassModel/Internal/AppScopedHaContextProvider.cs
Labels: pr: bugfix

#531 Add JsonPropertyName Attributes to Event class of HassModel
  src/HassModel/NetDeamon.HassModel/Common/Event.cs
Labels: pr: enhancement

#532 Added Error when using [Focus] while not in development
  src/DaemonRunner/DaemonRunner/Service/RunnerService.cs
Labels: pr: enhancement

#534 change readme to prepare for release
  README.md
Labels: pr: enhancement

#535 Remove beta from nuget versioning
  .github/workflows/push_nuget_manual.yml
  .github/workflows/tags_docker.yml
  .github/workflows/tags_nuget.yml
  src/App/NetDaemon.App/NetDaemon.App.csproj
  src/Daemon/NetDaemon.Daemon/NetDaemon.Daemon.csproj
  src/DaemonRunner/DaemonRunner/DaemonRunner.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling/NetDaemon.Extensions.Scheduling.csproj
  src/Fakes/NetDaemon.Fakes/NetDaemon.Fakes.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDeamon.HassModel/NetDaemon.HassModel.csproj
Labels: pr: enhancement

#536 Adds application context for apps
  src/App/NetDaemon.App/Common/ApplicationContexts/ApplicationContext.cs
  src/App/NetDaemon.App/Common/IApplicationContext.cs
  src/App/NetDaemon.App/DependencyInjectionSetup.cs
  tests/NetDaemon.Daemon.Tests/Daemon/AppContextTests.cs
  tests/NetDaemon.Daemon.Tests/GlobalUsings.cs
Labels: pr: new-feature
