Repository net-daemon/netdaemon, pull requests merged in 2021-04, with the labels that each got.

#339 Refactor NetDaemonHost.HandleNewEvent
  src/Daemon/NetDaemon.Daemon/Daemon/NetDaemonHost.cs
Labels: pr: enhancement

#343 maintainence of hass client
  src/App/NetDaemon.App/NetDaemon.App.csproj
  src/Daemon/NetDaemon.Daemon/NetDaemon.Daemon.csproj
  src/DaemonRunner/DaemonRunner/DaemonRunner.csproj
Labels: pr: bugfix, pr: dependency-update

#347 Fixed a bug. because the method CallServiceAsync was called with a dy…
  src/Daemon/NetDaemon.Daemon/Daemon/NetDaemonHost.cs
Labels: pr: bugfix

#355 Fixed codegen namespace to align with NetDaemon
  src/DaemonRunner/DaemonRunner/Service/RunnerService.cs
Labels: pr: enhancement

#358 Add label-check action to pull requests
  .github/workflows/check_pr_label.yml
Labels: pr: enhancement
