Repository net-daemon/netdaemon, pull requests merged in 2022-03, with the labels that each got.

#691 Better error handling and warnings for configuration
  dev/DebugHost/apps/Config/Config.yaml
  dev/DebugHost/apps/Config/ConfigApp.cs
  src/AppModel/NetDaemon.AppModel.Tests/Config/ConfigurationBinderTests.cs
  src/AppModel/NetDaemon.AppModel/Internal/Config/AppConfig.cs
  src/AppModel/NetDaemon.AppModel/Internal/Config/ConfigurationBinding.cs
Labels: pr: enhancement

#692 Dependecy upgrades
  src/AppModel/NetDaemon.AppModel.Tests/NetDaemon.AppModel.Tests.csproj
  src/AppModel/NetDaemon.AppModel/NetDaemon.AppModel.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/Runtime/NetDaemon.Runtime.Tests/NetDaemon.Runtime.Tests.csproj
Labels: pr: dependency-update

#693 Bugfix: Ensure entity_id is set as expected, when a name is provided
  src/Client/NetDaemon.HassClient.Tests/ExtensionsTest/MqttEntityManagerTests/EntityCreationPayloadHelperTests.cs
  src/Client/NetDaemon.HassClient.Tests/ExtensionsTest/MqttEntityManagerTests/MqttEntityManagerTester.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/Models/EntityCreationPayload.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/MqttEntityManager.cs
Labels: pr: bugfix

#694 Subscribe to MQTT topics and return Observable
  dev/DebugHost/apps/Extensions/MttEntitySubscriptionApp.cs
  src/Client/NetDaemon.HassClient.Tests/ExtensionsTest/MqttEntityManagerTests/ByteArrayHelperTests.cs
  src/Client/NetDaemon.HassClient.Tests/ExtensionsTest/MqttEntityManagerTests/MqttEntityManagerTester.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/DependencyInjectionSetup.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/Helpers/ByteArrayHelper.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/IMessageSubscriber.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/IMqttEntityManager.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/MessageSubscriber.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/Models/EntityCreationOptions.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/Models/EntityCreationPayload.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/MqttEntityManager.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/NetDaemon.Extensions.MqttEntityManager.csproj
Labels: pr: new-feature
