Repository net-daemon/netdaemon, pull requests merged in 2022-02, with the labels that each got.

#652 FocusFilter
  src/AppModel/NetDaemon.AppModel.Tests/AppModelTests.cs
  src/AppModel/NetDaemon.AppModel/Common/Extensions/ServiceCollectionExtension.cs
  src/AppModel/NetDaemon.AppModel/Internal/AppModelContext.cs
  src/AppModel/NetDaemon.AppModel/Internal/FocusFilter.cs
Labels: pr: enhancement

#653 Add background task tracking and proper error handling
  src/HassModel/NetDaemon.HassModel.Tests/Internal/AppScopedHaContextProviderTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/BackgroundTaskTrackerTests.cs
  src/HassModel/NetDeamon.HassModel/DependencyInjectionSetup.cs
  src/HassModel/NetDeamon.HassModel/Internal/AppScopedHaContextProvider.cs
  src/HassModel/NetDeamon.HassModel/Internal/BackgroundTaskTracker.cs
  src/HassModel/NetDeamon.HassModel/Internal/IBackgroundTaskTracker.cs
Labels: pr: enhancement

#655 Fix Cron taks were sometimes run twice due to clock skew
  src/Extensions/NetDaemon.Extensions.Scheduling/CronExtensions.cs
Labels: pr: bugfix

#654 Add snake casing to app input booleans
  src/Runtime/NetDaemon.Runtime.Tests/Internal/AppStateManagerTests.cs
  src/Runtime/NetDaemon.Runtime/Internal/AppStateManager.cs
Labels: pr: enhancement

#656 Initial commit of MQTT entity management framework.
  NetDaemon.Extensions.MqttEntities/DependencyInjectionSetup.cs
  NetDaemon.Extensions.MqttEntities/EntityUpdater.cs
  NetDaemon.Extensions.MqttEntities/IEntityUpdater.cs
  NetDaemon.Extensions.MqttEntities/IMessageSender.cs
  NetDaemon.Extensions.MqttEntities/MessageSender.cs
  NetDaemon.Extensions.MqttEntities/MqttConfiguration.cs
  NetDaemon.Extensions.MqttEntities/NetDaemon.Extensions.MqttEntities.csproj
  NetDaemon.sln
Labels: pr: new-feature

#657 Automatically remove unused app state input booleans
  src/Runtime/NetDaemon.Runtime.Tests/Internal/AppStateManagerTests.cs
  src/Runtime/NetDaemon.Runtime.Tests/Internal/AppStateRepositoryTests.cs
  src/Runtime/NetDaemon.Runtime.Tests/Internal/EntityMapperHelperTests.cs
  src/Runtime/NetDaemon.Runtime/Common/Extensions/ServiceBuilderExtensions.cs
  src/Runtime/NetDaemon.Runtime/Internal/AppStateManager.cs
  src/Runtime/NetDaemon.Runtime/Internal/AppStateRepository.cs
  src/Runtime/NetDaemon.Runtime/Internal/EntityMapperHelper.cs
  src/Runtime/NetDaemon.Runtime/Internal/HomeAssistantConnectionExtensions.cs
  src/Runtime/NetDaemon.Runtime/Internal/IAppStateRepository.cs
  src/Runtime/NetDaemon.Runtime/Internal/IHandleHomeAssistantAppStateUpdates.cs
  src/Runtime/NetDaemon.Runtime/Internal/Model/CreateInputBooleanHelperCommand.cs
  src/Runtime/NetDaemon.Runtime/Internal/NetDaemonRuntime.cs
Labels: pr: new-feature

#660 Adds nuget support
  .github/workflows/push_nuget_manual.yml
  .github/workflows/tags_nuget.yml
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/NetDaemon.Extensions.MqttEntityManager.csproj
  src/Host/NetDaemon.Host.Default/NetDaemon.Host.Default.csproj
  src/Host/NetDaemon.Host.Default/Program.cs
Labels: pr: enhancement

#658 Mqtt extension to create an update entities in HA
  .github/workflows/push_nuget_manual.yml
  .github/workflows/tags_nuget.yml
  NetDaemon.sln
  dev/DebugHost/DebugHost.csproj
  dev/DebugHost/Program.cs
  dev/DebugHost/Properties/launchSettings.json
  dev/DebugHost/apps/Extensions/MqttEntityManagerApp.cs
  dev/DebugHost/appsettings.json
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/DependencyInjectionSetup.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/Exceptions/MqttConnectionException.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/Exceptions/MqttPublishException.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/IMessageSender.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/IMqttEntityManager.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/MessageSender.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/MqttConfiguration.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/MqttEntityManager.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/NetDaemon.Extensions.MqttEntityManager.csproj
  src/Host/NetDaemon.Host.Default/NetDaemon.Host.Default.csproj
  src/Host/NetDaemon.Host.Default/Program.cs
Labels: pr: new-feature

#659 Adds specific naming rules for when is in development for input booleans app states
  src/Runtime/NetDaemon.Runtime.Tests/Internal/AppStateManagerTests.cs
  src/Runtime/NetDaemon.Runtime.Tests/Internal/AppStateRepositoryTests.cs
  src/Runtime/NetDaemon.Runtime.Tests/Internal/EntityMapperHelperTests.cs
  src/Runtime/NetDaemon.Runtime/Internal/AppStateManager.cs
  src/Runtime/NetDaemon.Runtime/Internal/AppStateRepository.cs
  src/Runtime/NetDaemon.Runtime/Internal/EntityMapperHelper.cs
Labels: pr: enhancement

#661 Added ExtensionMethods to codegen for calling service methods in IEnumerable<Entity>
  src/HassModel/NetDaemon.HassModel.CodeGenerator/ExtensionMethodsGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/ServiceArguments.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/ServicesGenerator.cs
  src/HassModel/NetDaemon.HassModel.Tests/Entities/EnumerableEntityExtensionsTest.cs
  src/HassModel/NetDeamon.HassModel/Entities/EnumerableEntityExtensions.cs
  src/HassModel/NetDeamon.HassModel/Internal/ExtensionMethods.cs
Labels: pr: new-feature

#665 fix: use lock when sending messages to ha
  src/Client/NetDaemon.HassClient/Internal/HomeAssistantConnection.cs
Labels: pr: bugfix

#666 SemaphoreSlim
  src/Client/NetDaemon.HassClient/Internal/HomeAssistantConnection.cs
Labels: pr: bugfix

#662 More optionality around entity creation, simplified public method signatures
  dev/DebugHost/apps/Extensions/MqttEntityManagerApp.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/Helpers/EntityIdParser.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/IMqttEntityManager.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/Models/EntityCreationOptions.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/Models/EntityCreationPayload.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/MqttEntityManager.cs
Labels: pr: enhancement

#667 Managed mqtt client, updated mqtt test app
  dev/DebugHost/apps/Extensions/MqttEntityManagerApp.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/AssuredMqttConnection.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/DependencyInjectionSetup.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/IAssuredMqttConnection.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/MessageSender.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/NetDaemon.Extensions.MqttEntityManager.csproj
Labels: pr: bugfix

#680 Extension method to wait for a state to be vald for a specific time
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/HassModel/NetDaemon.HassModel.Tests/StateObservableExtensionsTest.cs
  src/HassModel/NetDeamon.HassModel/StateObservableExtensions.cs
Labels: pr: new-feature

#677 Support dynamic options on MQTT entity creation
  dev/DebugHost/apps/Extensions/MqttEntityManagerApp.cs
  src/Client/NetDaemon.HassClient.Tests/ExtensionsTest/MqttEntityManagerTests/AssuredMqttConnectionTests.cs
  src/Client/NetDaemon.HassClient.Tests/ExtensionsTest/MqttEntityManagerTests/EntityCreationPayloadHelperTests.cs
  src/Client/NetDaemon.HassClient.Tests/ExtensionsTest/MqttEntityManagerTests/EntityIdParserTests.cs
  src/Client/NetDaemon.HassClient.Tests/ExtensionsTest/MqttEntityManagerTests/JsonNodeExtensionTests.cs
  src/Client/NetDaemon.HassClient.Tests/ExtensionsTest/MqttEntityManagerTests/MessageSenderTests.cs
  src/Client/NetDaemon.HassClient.Tests/ExtensionsTest/MqttEntityManagerTests/MqttEntityManagerTester.cs
  src/Client/NetDaemon.HassClient.Tests/ExtensionsTest/MqttEntityManagerTests/TestHelpers/MockMqttMessageSenderSetup.cs
  src/Client/NetDaemon.HassClient.Tests/NetDaemon.HassClient.Tests.csproj
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/AssuredMqttConnection.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/DependencyInjectionSetup.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/Helpers/EntityCreationPayloadHelper.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/Helpers/EntityIdParser.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/Helpers/IMqttFactoryWrapper.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/Helpers/JsonNodeExtensions.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/Helpers/MqttFactoryWrapper.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/IMessageSender.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/IMqttEntityManager.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/MessageSender.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/Models/EntityCreationOptions.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/Models/EntityCreationPayload.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/MqttEntityManager.cs
Labels: pr: new-feature

#686 Fixes the nuget push command
  .github/workflows/push_nuget_manual.yml
  .github/workflows/tags_nuget.yml
Labels: enhancement, pr: enhancement
