Repository net-daemon/netdaemon, pull requests merged in 2022-10, with the labels that each got.

#760 Versioning of assemblies match nuget package version
  .github/workflows/push_nuget_manual.yml
  .github/workflows/tags_nuget.yml
  src/AppModel/NetDaemon.AppModel.Tests/NetDaemon.AppModel.Tests.csproj
  src/AppModel/NetDaemon.AppModel/NetDaemon.AppModel.csproj
  src/Client/NetDaemon.HassClient.Tests/NetDaemon.HassClient.Tests.csproj
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/NetDaemon.Extensions.MqttEntityManager.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/NetDaemon.Extensions.Scheduling.Tests.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/Runtime/NetDaemon.Runtime.Tests/NetDaemon.Runtime.Tests.csproj
Labels: pr: enhancement, pr: dependency-update

#753 Make the generated files more friendly to code cleanup functionality of Visual Studio
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Generator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/TriviaHelper.cs
Labels: pr: enhancement

#762 Added MediaPlayerAttributesBase Class & Fixed Types in LightAttributesBase Class
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/NamingHelper.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Program.cs
  src/HassModel/NetDeamon.HassModel/Entities/Core/LightAttributesBase.cs
  src/HassModel/NetDeamon.HassModel/Entities/Core/MediaPlayerAttributesBase.cs
Labels: pr: new-feature

#764 Allow running NetDaemon in AspNetCore
  NetDaemon.sln
  dev/DebugHost/apps/HelloApp/HelloApp.cs
  src/AppModel/NetDaemon.AppModel.Tests/AppModelTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/Config/ConfigTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/Helpers/TestHelpers.cs
  src/AppModel/NetDaemon.AppModel/Common/IAppModel.cs
  src/AppModel/NetDaemon.AppModel/Common/IAppModelContext.cs
  src/AppModel/NetDaemon.AppModel/Internal/AppModel.cs
  src/AppModel/NetDaemon.AppModel/Internal/AppModelContext.cs
  src/Client/NetDaemon.HassClient/Internal/HomeAssistantRunner.cs
  src/Extensions/NetDaemon.Extensions.Logging/Internal/SerilogConfiguratior.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/AssuredMqttConnection.cs
  src/Runtime/NetDaemon.Runtime.Tests/Helpers/HomeAssistantRunnerMock.cs
  src/Runtime/NetDaemon.Runtime.Tests/Integration/TestRuntime.cs
  src/Runtime/NetDaemon.Runtime.Tests/Internal/NetDaemonRuntimeTests.cs
  src/Runtime/NetDaemon.Runtime/Common/Extensions/HostBuilderExtensions.cs
  src/Runtime/NetDaemon.Runtime/Common/Extensions/ServiceCollectionExtensions.cs
  src/Runtime/NetDaemon.Runtime/Common/IRuntime.cs
  src/Runtime/NetDaemon.Runtime/Internal/NetDaemonRuntime.cs
  src/Runtime/NetDaemon.Runtime/Internal/RuntimeService.cs
  src/debug/DebugHost/DebugHost.csproj
  src/debug/DebugHost/Program.cs
  src/debug/DebugHost/Properties/launchSettings.json
  src/debug/DebugHost/_appsettings.Development.json
  src/debug/DebugHost/apps/ConcurrencyTestApp.cs
  src/debug/DebugHost/apps/Config/Config.yaml
  src/debug/DebugHost/apps/Config/ConfigApp.cs
  src/debug/DebugHost/apps/Extensions/MqttEntityManagerApp.cs
  src/debug/DebugHost/apps/Extensions/MttEntitySubscriptionApp.cs
  src/debug/DebugHost/apps/HelloApp/HelloApp.cs
  src/debug/DebugHost/apps/YamlApp/YamlApp.cs
  src/debug/DebugHost/apps/YamlApp/YamlApp.yaml
  src/debug/DebugHost/appsettings.json
  src/debug/DebugWebHost/DebugWebHost.csproj
  src/debug/DebugWebHost/Program.cs
  src/debug/DebugWebHost/Properties/launchSettings.json
  src/debug/DebugWebHost/_appsettings.Development.json
  src/debug/DebugWebHost/appsettings.json
Labels: pr: new-feature
