Repository net-daemon/netdaemon, pull requests merged in 2022-07, with the labels that each got.

#721 Mqttnet 4
  src/Client/NetDaemon.HassClient.Tests/ExtensionsTest/MqttEntityManagerTests/MessageSenderTests.cs
  src/Client/NetDaemon.HassClient.Tests/ExtensionsTest/MqttEntityManagerTests/TestHelpers/MockMqttMessageSenderSetup.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/AssuredMqttConnection.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/DependencyInjectionSetup.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/Helpers/MqttFactoryWrapper.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/IMqttFactory.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/MessageSender.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/MessageSubscriber.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/MqttFactoryFactory.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/NetDaemon.Extensions.MqttEntityManager.csproj
Labels: pr: dependency-update

#727 Checks if fields value type is object before enumerate objects on service property.
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Model/JsonExtensions.cs
Labels: pr: bugfix

#702 Adds Folder placement for generated code and File Per Entity generation.
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGenerationSettings.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Extensions/CodeGeneratorExtensions.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Generator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Program.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/_appsettings.Development.json
  src/HassModel/NetDaemon.HassModel.CodeGenerator/appsettings.json
Labels: pr: new-feature
