Repository net-daemon/netdaemon, pull requests merged in 2022-01, with the labels that each got.

#569 Solid error handling and logging
  NetDaemon.sln
  src/AppModel/NetDaemon.AppModel.Tests/AppModelTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/AssemblyResolver/AssemblyResolverTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/Compiler/CompilerIntegrationTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/Config/ConfigTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/Fixtures/LocalError/LocalApp.cs
  src/AppModel/NetDaemon.AppModel.Tests/Helpers/TestHelpers.cs
  src/AppModel/NetDaemon.AppModel.Tests/TypeResolver/TypeResolverTests.cs
  src/AppModel/NetDaemon.AppModel/Common/Extensions/ServiceCollectionExtension.cs
  src/AppModel/NetDaemon.AppModel/Internal/AppModel.cs
  src/AppModel/NetDaemon.AppModel/Internal/Compiler/SyntaxTreeResolver.cs
  src/AppModel/NetDaemon.AppModel/Internal/Config/ConfigurationBinding.cs
  src/AppModel/NetDaemon.AppModel/Internal/Config/Yaml/YamlConfigurationFileParser.cs
  src/Client/NetDaemon.HassClient/Common/Extensions/ServiceCollectionExtension.cs
  src/Client/NetDaemon.HassClient/GlobalUsings.cs
  src/Client/NetDaemon.HassClient/Internal/HomeAssistantConnection.cs
  src/DevelopmentApps/v3apps/HelloWorld/Hello_world_app.cs
  src/DevelopmentApps/v3apps/ThrowsExceptionApp.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/AppScopedHaContextProviderTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/AppScopedHaContextProviderUsingClientTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/ScopedObservableTests.cs
  src/HassModel/NetDaemon.HassModel.Tests/TestHelpers/Extensions.cs
  src/HassModel/NetDaemon.HassModel.Tests/TestHelpers/MockInvocationWaiter.cs
  src/HassModel/NetDeamon.HassModel/Internal/Client/AppScopedHaContextProvider.cs
  src/HassModel/NetDeamon.HassModel/Internal/Client/EntityStateCache.cs
  src/HassModel/NetDeamon.HassModel/Internal/Extensions/ObservableExtensions.cs
  src/HassModel/NetDeamon.HassModel/Internal/HassClient/AppScopedHaContextProvider.cs
  src/HassModel/NetDeamon.HassModel/Internal/ScopedObservable.cs
  src/Host/NetDaemon.Host.Default/Program.cs
  src/Runtime/NetDaemon.Runtime.Tests/Fixtures/LocalApp.cs
  src/Runtime/NetDaemon.Runtime.Tests/GlobalUsings.cs
  src/Runtime/NetDaemon.Runtime.Tests/Helpers/HomeAssistantRunnerMock.cs
  src/Runtime/NetDaemon.Runtime.Tests/Helpers/MoqExtensions.cs
  src/Runtime/NetDaemon.Runtime.Tests/Helpers/TestSettings.cs
  src/Runtime/NetDaemon.Runtime.Tests/Integration/TestRuntime.cs
  src/Runtime/NetDaemon.Runtime.Tests/NetDaemon.Runtime.Tests.csproj
  src/Runtime/NetDaemon.Runtime.Tests/appsettings.json
  src/Runtime/NetDaemon.Runtime/Common/Extensions/HostBuilderExtensions.cs
  src/Runtime/NetDaemon.Runtime/Common/IRuntime.cs
  src/Runtime/NetDaemon.Runtime/GlobalUsings.cs
  src/Runtime/NetDaemon.Runtime/Internal/NetDaemonRuntime.cs
  src/Runtime/NetDaemon.Runtime/Internal/RuntimeService.cs
  src/Runtime/NetDaemon.Runtime/NetDaemon.Runtime.csproj
Labels: pr: enhancement

#571 Codegen uses short typenames with using in stead of fully quatified names
  src/DaemonRunner/DaemonRunner/DaemonRunner.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGenerationSettings.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/EntitiesGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/EntitySet.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/ExtensionMethodsGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Extensions/CollectionExtensions.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Extensions/StringExtensions.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Extensions/SyntaxFactoryExtensions.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Extensions/TypeExtensions.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Generator.Entitites.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Generator.ExtensionMethods.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Generator.Services.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Generator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/GlobalUsings.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/EntityIdHelper.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/HassServiceArgumentMapper.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/HomeAssistantSettings.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/NamingHelper.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/SyntaxFactoryHelper.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Program.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/ServiceArguments.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/ServicesGenerator.cs
Labels: pr: enhancement

#574 Add IApplication and AppModelContext
  src/AppModel/NetDaemon.AppModel.Tests/AppModelTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/Config/ConfigTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/Helpers/TestHelpers.cs
  src/AppModel/NetDaemon.AppModel/Common/ApplicationState.cs
  src/AppModel/NetDaemon.AppModel/Common/IAppModel.cs
  src/AppModel/NetDaemon.AppModel/Common/IAppModelContext.cs
  src/AppModel/NetDaemon.AppModel/Common/IApplication.cs
  src/AppModel/NetDaemon.AppModel/Common/IApplicationInstance.cs
  src/AppModel/NetDaemon.AppModel/Internal/AppModel.cs
  src/AppModel/NetDaemon.AppModel/Internal/AppModelContext.cs
  src/AppModel/NetDaemon.AppModel/Internal/Application.cs
  src/AppModel/NetDaemon.AppModel/Internal/Context/ApplicationContext.cs
  src/AppModel/NetDaemon.AppModel/Internal/Context/IApplicationContext.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/ScopedObservableTests.cs
  src/Runtime/NetDaemon.Runtime/Internal/NetDaemonRuntime.cs
Labels: pr: enhancement

#575 Avoid Dispose[Async]() from being called multiple times.
  src/App/NetDaemon.App/Common/ApplicationContexts/ApplicationContext.cs
Labels: pr: bugfix

#577 Fix so Entities are resolved in config
  src/AppModel/NetDaemon.AppModel.Tests/Config/ConfigTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/Fixtures/Local/LocalApp.cs
  src/AppModel/NetDaemon.AppModel.Tests/Fixtures/Local/settings.yaml
  src/AppModel/NetDaemon.AppModel/Common/Extensions/ServiceCollectionExtension.cs
  src/AppModel/NetDaemon.AppModel/Internal/Config/ConfigurationBinding.cs
  src/DevelopmentApps/v3apps/YamlAppWithConfig/YamlAppWithConfig.cs
  src/DevelopmentApps/v3apps/YamlAppWithConfig/YamlAppWithConfig.yaml
Labels: pr: enhancement

#579 Added state management to appmodel
  src/AppModel/NetDaemon.AppModel.Tests/AppModelTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/Config/ConfigTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/Helpers/TestHelpers.cs
  src/AppModel/NetDaemon.AppModel/Common/ApplicationState.cs
  src/AppModel/NetDaemon.AppModel/Common/IAppStateManager.cs
  src/AppModel/NetDaemon.AppModel/Common/IApplication.cs
  src/AppModel/NetDaemon.AppModel/Internal/AppModel.cs
  src/AppModel/NetDaemon.AppModel/Internal/AppModelContext.cs
  src/AppModel/NetDaemon.AppModel/Internal/Application.cs
  src/AppModel/NetDaemon.AppModel/Internal/IAsyncInitializable.cs
Labels: pr: enhancement

#580 Add runtime parts for app state management
  src/AppModel/NetDaemon.AppModel/Internal/AppModelContext.cs
  src/AppModel/NetDaemon.AppModel/Internal/Application.cs
  src/AppModel/NetDaemon.AppModel/Internal/Context/ApplicationContext.cs
  src/HassModel/NetDaemon.HassModel.Integration/IntegrationHaContextExtensions.cs
  src/HassModel/NetDaemon.HassModel.Tests/Integration/IntegrationHaContextExtensionsTests.cs
  src/Host/NetDaemon.Host.Default/Program.cs
  src/Runtime/NetDaemon.Runtime/Common/Extensions/ServiceBuilderExtensions.cs
  src/Runtime/NetDaemon.Runtime/Internal/AppStateManager.cs
  src/Runtime/NetDaemon.Runtime/Internal/NetDaemonRuntime.cs
  src/Runtime/NetDaemon.Runtime/NetDaemon.Runtime.csproj
Labels: pr: enhancement

#581 Add tests and cleanup
  .github/workflows/ci_app_model.yml
  src/AppModel/NetDaemon.AppModel.Tests/AppModelTests.cs
  src/AppModel/NetDaemon.AppModel/Common/IApplication.cs
  src/AppModel/NetDaemon.AppModel/Internal/AppModel.cs
  src/AppModel/NetDaemon.AppModel/Internal/Application.cs
  src/Client/NetDaemon.HassClient/Internal/HomeAssistantRunner.cs
  src/HassModel/NetDaemon.HassModel.Integration/IntegrationHaContextExtensions.cs
  src/HassModel/NetDaemon.HassModel.Tests/Integration/IntegrationHaContextExtensionsTests.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/AppScopedHaContextProviderTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/AppScopedHaContextProviderUsingClientTest.cs
  src/HassModel/NetDeamon.HassModel/NetDaemon.HassModel.csproj
  src/Runtime/NetDaemon.Runtime.Tests/GlobalUsings.cs
  src/Runtime/NetDaemon.Runtime.Tests/Integration/TestRuntime.cs
  src/Runtime/NetDaemon.Runtime.Tests/Internal/AppStateManagerTests.cs
  src/Runtime/NetDaemon.Runtime.Tests/Internal/NetDaemonRuntimeTests.cs
  src/Runtime/NetDaemon.Runtime.Tests/NetDaemon.Runtime.Tests.csproj
  src/Runtime/NetDaemon.Runtime/Common/IRuntime.cs
  src/Runtime/NetDaemon.Runtime/GlobalUsings.cs
  src/Runtime/NetDaemon.Runtime/Internal/AppStateManager.cs
  src/Runtime/NetDaemon.Runtime/Internal/IHandleHomeAssistantAppStateUpdates.cs
  src/Runtime/NetDaemon.Runtime/Internal/NetDaemonRuntime.cs
Labels: pr: enhancement

#572 Added HassModel CacheManager
  src/HassModel/NetDaemon.HassModel.Tests/Internal/AppScopedHaContextProviderTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/AppScopedHaContextProviderUsingClientTest.cs
  src/HassModel/NetDeamon.HassModel/Common/ICacheManager.cs
  src/HassModel/NetDeamon.HassModel/DependencyInjectionSetup.cs
  src/HassModel/NetDeamon.HassModel/Internal/Client/CacheManager.cs
  src/Runtime/NetDaemon.Runtime.Tests/Internal/NetDaemonRuntimeTests.cs
  src/Runtime/NetDaemon.Runtime/Internal/NetDaemonRuntime.cs
Labels: pr: enhancement

#584 Re-add the developmen apps project
  .vscode/launch.json
  NetDaemon.sln
  dev/DebugHost/DebugHost.csproj
  dev/DebugHost/Program.cs
  dev/DebugHost/_appsettings.Development.json
  dev/DebugHost/apps/HellApp/HelloApp.cs
  dev/DebugHost/apps/HellApp/YamlApp/YamlApp.cs
  dev/DebugHost/apps/HellApp/YamlApp/YamlApp.yaml
  dev/DebugHost/appsettings.json
Labels: pr: enhancement

#583 Avoid DisposeAsync from being called multiple times.
  src/AppModel/NetDaemon.AppModel.Tests/AppModelTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/Context/ApplicationScopeTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/Fixtures/Local/LocalAppWithDisposable.cs
  src/AppModel/NetDaemon.AppModel/Internal/Application.cs
  src/AppModel/NetDaemon.AppModel/Internal/Context/ApplicationContext.cs
  src/AppModel/NetDaemon.AppModel/Internal/Context/IApplicationContext.cs
  src/AppModel/NetDaemon.AppModel/NetDaemon.AppModel.csproj
Labels: pr: bugfix

#585 Fix docker image creation
  .github/workflows/push_docker_dev.yml
  .github/workflows/push_docker_manual.yml
  .github/workflows/push_nuget_manual.yml
  .github/workflows/tags_docker.yml
  .github/workflows/tags_nuget.yml
  .github/workflows/test_docker.yml
  Docker/rootfs/etc/services.d/NetDaemonApp/run
  Dockerfile
  src/Host/NetDaemon.Host.Default/Program.cs
Labels: pr: enhancement

#589 Adds concurrency between apps
  dev/DebugHost/DebugHost.csproj
  dev/DebugHost/Program.cs
  dev/DebugHost/_appsettings.Development.json
  dev/DebugHost/apps/ConcurrencyTestApp.cs
  dev/DebugHost/apps/HellApp/HelloApp.cs
  dev/DebugHost/apps/HelloApp/HelloApp.cs
  dev/DebugHost/apps/YamlApp/YamlApp.cs
  dev/DebugHost/apps/YamlApp/YamlApp.yaml
  dev/DebugHost/appsettings.json
  src/Client/NetDaemon.HassClient/Internal/HomeAssistantRunner.cs
  src/HassModel/NetDaemon.HassModel.Tests/Common/ObservableExtensionsTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/AppScopedHaContextProviderTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/AppScopedHaContextProviderUsingClientTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/EntityStateCacheUsingClientTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/QueuedObservableTests.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/ScopedObservableTests.cs
  src/HassModel/NetDaemon.HassModel.Tests/TestHelpers/Extensions.cs
  src/HassModel/NetDaemon.HassModel.Tests/TestHelpers/MockInvocationWaiter.cs
  src/HassModel/NetDaemon.HassModel.Tests/TestHelpers/NonQueuedObservableMock.cs
  src/HassModel/NetDeamon.HassModel/Common/IQueuedObservable.cs
  src/HassModel/NetDeamon.HassModel/Common/ObservableExtensions.cs
  src/HassModel/NetDeamon.HassModel/DependencyInjectionSetup.cs
  src/HassModel/NetDeamon.HassModel/Internal/Client/AppScopedHaContextProvider.cs
  src/HassModel/NetDeamon.HassModel/Internal/Client/EntityAreaCache.cs
  src/HassModel/NetDeamon.HassModel/Internal/Client/EntityStateCache.cs
  src/HassModel/NetDeamon.HassModel/Internal/QueuedObservable.cs
  src/HassModel/NetDeamon.HassModel/Internal/ScopedObservable.cs
  src/Runtime/NetDaemon.Runtime.Tests/Helpers/MoqExtensions.cs
  src/Runtime/NetDaemon.Runtime.Tests/Helpers/NonQueuedObservableMock.cs
  src/Runtime/NetDaemon.Runtime.Tests/Helpers/ObservableExtensions.cs
  src/Runtime/NetDaemon.Runtime.Tests/Integration/TestRuntime.cs
  src/Runtime/NetDaemon.Runtime.Tests/Internal/AppStateManagerTests.cs
  src/Runtime/NetDaemon.Runtime.Tests/Internal/NetDaemonRuntimeTests.cs
Labels: pr: enhancement

#590 Flush channel in QueuedObservable.DisposeAsync()
  src/HassModel/NetDaemon.HassModel.Tests/Internal/AppScopedHaContextProviderUsingClientTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/QueuedObservabeTest.cs
  src/HassModel/NetDeamon.HassModel/Internal/Client/AppScopedHaContextProvider.cs
  src/HassModel/NetDeamon.HassModel/Internal/QueuedObservable.cs
Labels: pr: enhancement

#591 Add app from type
  src/AppModel/NetDaemon.AppModel.Tests/AssemblyResolver/AssemblyResolverTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/TypeResolver/TypeResolverTests.cs
  src/AppModel/NetDaemon.AppModel/Common/Extensions/ServiceCollectionExtension.cs
  src/AppModel/NetDaemon.AppModel/Internal/IAsyncInitializable.cs
  src/AppModel/NetDaemon.AppModel/Internal/TypeResolver/SingleAppResolver.cs
  src/Runtime/NetDaemon.Runtime.Tests/Integration/TestRuntime.cs
Labels: pr: enhancement

#592 Merge queued tests and fix AddAppFromType
  src/AppModel/NetDaemon.AppModel/Common/Extensions/ServiceCollectionExtension.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/QueuedObservabeTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/QueuedObservableTests.cs
  src/Runtime/NetDaemon.Runtime.Tests/Integration/TestRuntime.cs
  src/Runtime/NetDaemon.Runtime.Tests/Internal/NetDaemonRuntimeTests.cs
  src/Runtime/NetDaemon.Runtime/Internal/NetDaemonRuntime.cs
Labels: pr: enhancement, pr: bugfix

#594 Adds [Focus] attribute support
  dev/DebugHost/apps/HelloApp/HelloApp.cs
  src/AppModel/NetDaemon.AppModel.Tests/AppModelTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/Fixtures/DynamicWithFocus/Application.cs
  src/AppModel/NetDaemon.AppModel.Tests/NetDaemon.AppModel.Tests.csproj
  src/AppModel/NetDaemon.AppModel/Internal/AppModelContext.cs
  src/AppModel/NetDaemon.AppModel/Internal/Application.cs
  src/Runtime/NetDaemon.Runtime/Internal/AppStateManager.cs
  src/Runtime/NetDaemon.Runtime/Internal/NetDaemonRuntime.cs
Labels: pr: enhancement

#595 Adds default logging to new AppModel
  .github/workflows/push_nuget_manual.yml
  .github/workflows/tags_nuget.yml
  NetDaemon.sln
  dev/DebugHost/DebugHost.csproj
  dev/DebugHost/Program.cs
  dev/DebugHost/_appsettings.Development.json
  dev/DebugHost/appsettings.json
  src/Extensions/NetDaemon.Extensions.Logging/Common/ServiceCollectionExtensions.cs
  src/Extensions/NetDaemon.Extensions.Logging/Internal/LoggingConfiguration.cs
  src/Extensions/NetDaemon.Extensions.Logging/Internal/NetDaemonLoggingThemes.cs
  src/Extensions/NetDaemon.Extensions.Logging/Internal/SerilogConfiguratior.cs
  src/Extensions/NetDaemon.Extensions.Logging/NetDaemon.Extensions.Logging.csproj
  src/Host/NetDaemon.Host.AddOn/Internal/Extensions/HostBuilderExtension.cs
  src/Host/NetDaemon.Host.AddOn/NetDaemon.Host.AddOn.csproj
  src/Host/NetDaemon.Host.AddOn/appsettings.json
  src/Host/NetDaemon.Host.Default/NetDaemon.Host.Default.csproj
  src/Host/NetDaemon.Host.Default/Program.cs
  src/Host/NetDaemon.Host.Default/appsettings.json
Labels: pr: enhancement

#597 Add CI fixes
  .github/workflows/push_docker_dev.yml
  .github/workflows/push_docker_manual.yml
  .github/workflows/tags_docker.yml
  .github/workflows/tags_nuget.yml
Labels: pr: enhancement

#599 Removes HassClient from HassModel
  src/HassModel/NetDaemon.HassModel.CodeGenerator/EntitiesGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/EntitySet.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/ExtensionMethodsGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Generator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/GlobalUsings.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Model/HassService.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Model/HassServiceDomain.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Model/HassServiceField.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Model/JsonExtensions.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Model/NullableEnumStringConverter.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Model/Selectors.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Model/SnakeCaseNamingPolicy.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Program.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/CodeGeneratorTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Entities/EntityTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Entities/NumericEntityTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/AppScopedHaContextProviderTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/AppScopedHaContextProviderUsingClientTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/EntityAreaCachTests.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/EntityAreaCacheTests.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/EntityStateCacheTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/EntityStateCacheUsingClientTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/QueuedObservabeTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/ScopedObservableTests.cs
  src/HassModel/NetDaemon.HassModel.Tests/TestHelpers/Extensions.cs
  src/HassModel/NetDeamon.HassModel/Common/Event.cs
  src/HassModel/NetDeamon.HassModel/Common/HaContextExtensions.cs
  src/HassModel/NetDeamon.HassModel/DependencyInjectionSetup.cs
  src/HassModel/NetDeamon.HassModel/Entities/Entity.cs
  src/HassModel/NetDeamon.HassModel/Entities/EntityState.cs
  src/HassModel/NetDeamon.HassModel/Internal/AppScopedHaContextProvider.cs
  src/HassModel/NetDeamon.HassModel/Internal/CacheManager.cs
  src/HassModel/NetDeamon.HassModel/Internal/EntityAreaCache.cs
  src/HassModel/NetDeamon.HassModel/Internal/EntityStateCache.cs
  src/HassModel/NetDeamon.HassModel/Internal/ExtensionMethods.cs
  src/HassModel/NetDeamon.HassModel/Internal/Extensions/ObservableExtensions.cs
  src/HassModel/NetDeamon.HassModel/Internal/HassClient/AppScopedHaContextProvider.cs
  src/HassModel/NetDeamon.HassModel/Internal/HassClient/EntityAreaCache.cs
  src/HassModel/NetDeamon.HassModel/Internal/HassClient/EntityStateCache.cs
  src/HassModel/NetDeamon.HassModel/Internal/HassClient/HassObjectMapper.cs
  src/HassModel/NetDeamon.HassModel/Internal/HassObjectMapper.cs
  src/HassModel/NetDeamon.HassModel/Internal/QueuedObservable.cs
  src/HassModel/NetDeamon.HassModel/Internal/ScopedObservable.cs
  src/HassModel/NetDeamon.HassModel/NetDaemon.HassModel.csproj
  src/Runtime/NetDaemon.Runtime.Tests/Internal/NetDaemonRuntimeTests.cs
  src/Runtime/NetDaemon.Runtime/Common/Extensions/HostBuilderExtensions.cs
Labels: pr: enhancement

#600 Remove app_model branch specific things from CI
  .github/workflows/ci_app_model.yml
  .github/workflows/push_docker_dev.yml
  src/HassModel/NetDaemon.HassModel.Tests/Internal/QueuedObservabeTest.cs
Labels: pr: enhancement

#603 Introduce a appstate cache in StateManager
  src/Client/NetDaemon.HassClient.Tests/ExtensionsTest/HomeAssistantApiManagerExtensionTests.cs
  src/Client/NetDaemon.HassClient/Common/HomeAssistant/Extensions/IHomeAssistantApiManagerExtensions.cs
  src/Runtime/NetDaemon.Runtime/Internal/AppStateManager.cs
Labels: pr: bugfix

#605 Fix SetEntityStateAsync and GetEntityStateAsync
  src/Client/NetDaemon.HassClient.Tests/ExtensionsTest/HomeAssistantApiManagerExtensionTests.cs
  src/Client/NetDaemon.HassClient/Common/HomeAssistant/Extensions/IHomeAssistantApiManagerExtensions.cs
Labels: pr: bugfix

#604 Added support for async initialization
  src/AppModel/NetDaemon.AppModel.Tests/AppModelTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/Fixtures/Local/LocalAppWithInitializeAsync.cs
  src/AppModel/NetDaemon.AppModel/Common/IAsyncInitializable.cs
  src/AppModel/NetDaemon.AppModel/Internal/Application.cs
  src/AppModel/NetDaemon.AppModel/Internal/Context/ApplicationContext.cs
  src/AppModel/NetDaemon.AppModel/Internal/IAsyncInitializable.cs
Labels: pr: new-feature

#606 Add scheduling to default and addon hosts
  src/Host/NetDaemon.Host.AddOn/Internal/Extensions/HostBuilderExtension.cs
  src/Host/NetDaemon.Host.AddOn/NetDaemon.Host.AddOn.csproj
  src/Host/NetDaemon.Host.Default/NetDaemon.Host.Default.csproj
  src/Host/NetDaemon.Host.Default/Program.cs
Labels: pr: bugfix

#607 some-bugfixes-and-stuff
  src/AppModel/NetDaemon.AppModel/Internal/Config/AppConfig.cs
  src/Client/NetDaemon.HassClient.Tests/Integration/IntegrationTestBase.cs
  src/Client/NetDaemon.HassClient.Tests/Net/WebSocketTransportPipelineTests.cs
  src/Client/NetDaemon.HassClient/Common/HomeAssistantClientConnector.cs
  src/Client/NetDaemon.HassClient/Internal/HomeAssistantClient.cs
  src/Client/NetDaemon.HassClient/Internal/HomeAssistantRunner.cs
  src/Client/NetDaemon.HassClient/Internal/Net/WebSocketTransportPipeline.cs
  src/Client/NetDaemon.HassClient/Internal/Net/WebSocketTransportPipelineFactory.cs
  src/Runtime/NetDaemon.Runtime/Internal/NetDaemonRuntime.cs
Labels: pr: enhancement, pr: bugfix

#608 Add text to speech extensions
  .github/workflows/push_nuget_manual.yml
  .github/workflows/tags_nuget.yml
  NetDaemon.sln
  dev/DebugHost/DebugHost.csproj
  dev/DebugHost/Program.cs
  src/Extensions/NetDaemon.Extensions.Tts/GlobalUsings.cs
  src/Extensions/NetDaemon.Extensions.Tts/HostBuilderExtensions.cs
  src/Extensions/NetDaemon.Extensions.Tts/ITextToSpeechService.cs
  src/Extensions/NetDaemon.Extensions.Tts/Internal/TextToSpeechService.cs
  src/Extensions/NetDaemon.Extensions.Tts/Internal/TtsMessage.cs
  src/Extensions/NetDaemon.Extensions.Tts/NetDaemon.Extensions.Tts.csproj
  src/Host/NetDaemon.Host.AddOn/Internal/Extensions/HostBuilderExtension.cs
  src/Host/NetDaemon.Host.AddOn/NetDaemon.Host.AddOn.csproj
  src/Host/NetDaemon.Host.AddOn/Program.cs
  src/Host/NetDaemon.Host.AddOn/appsettings.json
  src/Host/NetDaemon.Host.Default/NetDaemon.Host.Default.csproj
  src/Host/NetDaemon.Host.Default/Program.cs
Labels: pr: new-feature

#609 Fix Tts extension connection restart
  src/Extensions/NetDaemon.Extensions.Tts/Internal/TextToSpeechService.cs
Labels: pr: bugfix

#611 Remove leading 0 in week number
  .github/workflows/release_drafter.yml
Labels: pr: enhancement

#610 Register service when using the dynamically compiled code option
  src/AppModel/NetDaemon.AppModel.Tests/AppModelTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/AssemblyResolver/AssemblyResolverTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/Compiler/CompilerIntegrationTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/Fixtures/DynamicWithServiceCollection/Application.cs
  src/AppModel/NetDaemon.AppModel.Tests/Helpers/TestHelpers.cs
  src/AppModel/NetDaemon.AppModel.Tests/NetDaemon.AppModel.Tests.csproj
  src/AppModel/NetDaemon.AppModel.Tests/TypeResolver/TypeResolverTests.cs
  src/AppModel/NetDaemon.AppModel/Common/Attributes/ServiceCollectionExtensionAttribute.cs
  src/AppModel/NetDaemon.AppModel/Common/Extensions/ServiceCollectionExtension.cs
  src/AppModel/NetDaemon.AppModel/Internal/AssemblyResolver/AssemblyResolver.cs
Labels: pr: new-feature

#612 Fix #560 Device with all numeric name cannot be deserialized
  src/Client/NetDaemon.HassClient.Tests/Json/HassDeviceConverterTests.cs
  src/Client/NetDaemon.HassClient/Common/HomeAssistant/Model/HassDevice.cs
  src/Client/NetDaemon.HassClient/Internal/Json/ReadNumberAsStringConverter.cs
Labels: pr: bugfix

#613 Use input booleans instead of switch for app state
  src/Client/NetDaemon.HassClient/Common/Exceptions/HomeAssistantApiCallException.cs
  src/Client/NetDaemon.HassClient/Common/IHomeAssistantConnection.cs
  src/Client/NetDaemon.HassClient/Internal/HomeAssistant/Commands/CreateHelperCommandBase.cs
  src/Client/NetDaemon.HassClient/Internal/HomeAssistantApiManager.cs
  src/Runtime/NetDaemon.Runtime.Tests/Internal/AppStateManagerTests.cs
  src/Runtime/NetDaemon.Runtime/Internal/AppStateManager.cs
  src/Runtime/NetDaemon.Runtime/Internal/HomeAssistantConnectionExtensions.cs
  src/Runtime/NetDaemon.Runtime/Internal/Model/CreateInputBooleanHelperCommand.cs
  src/Runtime/NetDaemon.Runtime/Internal/Model/HassHelper.cs
Labels: pr: enhancement

#615 Set correct log level in add-on
  src/Host/NetDaemon.Host.AddOn/Internal/Extensions/HostBuilderExtension.cs
  src/Host/NetDaemon.Host.AddOn/Internal/Helpers/LogLevelParser.cs
  src/Host/NetDaemon.Host.AddOn/NetDaemon.Host.AddOn.csproj
  src/Host/NetDaemon.Host.AddOn/Program.cs
Labels: pr: bugfix

#616 Bugfix: Restart issue
  src/Runtime/NetDaemon.Runtime/Internal/AppStateManager.cs
  src/Runtime/NetDaemon.Runtime/Internal/NetDaemonRuntime.cs
Labels: pr: bugfix

#617 Adding V3 info to readme
  README.md
Labels: pr: enhancement

#618 Fix release on tag for V3
  .github/workflows/tags_docker.yml
Labels: pr: enhancement

#621 Added HA add-on support the proper way
  Docker/rootfs/etc/services.d/NetDaemonAddOnApp/run
  Dockerfile
  Dockerfile.AddOn
  NetDaemon.sln
  src/Host/NetDaemon.Host.AddOn/Internal/Config/PluginConfig.cs
  src/Host/NetDaemon.Host.AddOn/Internal/Extensions/HostBuilderExtension.cs
  src/Host/NetDaemon.Host.AddOn/Internal/Extensions/ServiceCollectionExtensions.cs
  src/Host/NetDaemon.Host.AddOn/Internal/Helpers/LogLevelParser.cs
  src/Host/NetDaemon.Host.AddOn/NetDaemon.Host.AddOn.csproj
  src/Host/NetDaemon.Host.AddOn/Program.cs
  src/Host/NetDaemon.Host.AddOn/appsettings.json
Labels: pr: enhancement

#622 Fix versioning substitution with reusable GH action
  .github/workflows/common/set_netdaemon_version.yml
  .github/workflows/push_docker_dev.yml
  .github/workflows/push_docker_manual.yml
  .github/workflows/tags_docker.yml
Labels: pr: bugfix

#625 Ignore certificate errors for hash support
  dev/DebugHost/_appsettings.Development.json
  dev/DebugHost/appsettings.json
  src/Client/NetDaemon.HassClient.Debug/_appsettings.Development.json
  src/Client/NetDaemon.HassClient.Debug/appsettings.json
  src/Client/NetDaemon.HassClient.Tests/HelperTest/HttpHandlerHelperTests.cs
  src/Client/NetDaemon.HassClient.Tests/Integration/IntegrationTestBase.cs
  src/Client/NetDaemon.HassClient.Tests/Net/WebSocketClientFactoryTests.cs
  src/Client/NetDaemon.HassClient/Common/Extensions/ServiceCollectionExtension.cs
  src/Client/NetDaemon.HassClient/Common/HomeAssistantClientConnector.cs
  src/Client/NetDaemon.HassClient/Common/Settings/Settings.cs
  src/Client/NetDaemon.HassClient/Internal/Helpers/HttpHelper.cs
  src/Client/NetDaemon.HassClient/Internal/Net/WebSocketClientFactory.cs
  src/Client/NetDaemon.HassClient/Internal/Net/WebSocketClientImpl.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/HomeAssistantSettings.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Program.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/_appsettings.Development.json
  src/Host/NetDaemon.Host.Default/appsettings.json
Labels: pr: new-feature

#626 Fix error prohibit start using custom built assembly
  Docker/rootfs/etc/services.d/NetDaemonAddOnApp/run
Labels: pr: bugfix

#627 Bugfix: Adding single type will prevent loading the whole assembly
  src/AppModel/NetDaemon.AppModel.Tests/TypeResolver/TypeResolverTests.cs
  src/AppModel/NetDaemon.AppModel/Common/Extensions/ServiceCollectionExtension.cs
Labels: pr: bugfix

#629 Force ssl==false for add-on
  Docker/rootfs/etc/services.d/NetDaemonAddOnApp/run
Labels: pr: bugfix

#630 Re-add the integration tests
  .github/workflows/ci_integration_tests.yaml
  tests/Integration/HA/config/configuration.yaml
  tests/Integration/NetDaemon.Tests.Integration/BasicTest.cs
  tests/Integration/NetDaemon.Tests.Integration/Helpers/TestFixture.cs
  tests/Integration/NetDaemon.Tests.Integration/NetDaemon.Tests.Integration.csproj
  tests/Integration/NetDaemon.Tests.Integration/Startup.cs
  tests/Integration/NetDaemon.Tests.Integration/_appsettings.Development.json
  tests/Integration/NetDaemon.Tests.Integration/apps/Config.yaml
  tests/Integration/NetDaemon.Tests.Integration/appsettings.json
Labels: pr: new-feature

#632 Fix the environment variable to be consistent
  Docker/rootfs/etc/services.d/NetDaemonApp/run
Labels: bug, pr: bugfix

#634 Relative paths does not load in some scenarios
  src/AppModel/NetDaemon.AppModel/Internal/Compiler/SyntaxTreeResolver.cs
  src/Runtime/NetDaemon.Runtime/Common/Extensions/HostBuilderExtensions.cs
Labels: pr: bugfix

#635 fix: add missing brackets
  Docker/rootfs/etc/services.d/NetDaemonApp/run
Labels: pr: bugfix

#636 Add HassModel.Integration to default host
  src/Host/NetDaemon.Host.Default/NetDaemon.Host.Default.csproj
Labels: pr: bugfix

#637 Add debug support for dynamic compiled apps
  dev/DebugHost/Program.cs
  src/AppModel/NetDaemon.AppModel.Tests/Compiler/CompilerIntegrationTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/TypeResolver/TypeResolverTests.cs
  src/AppModel/NetDaemon.AppModel/Common/Extensions/ServiceCollectionExtension.cs
  src/AppModel/NetDaemon.AppModel/Internal/AssemblyResolver/AssemblyResolver.cs
  src/AppModel/NetDaemon.AppModel/Internal/Compiler/CompileSettings.cs
  src/AppModel/NetDaemon.AppModel/Internal/Compiler/Compiler.cs
  src/AppModel/NetDaemon.AppModel/Internal/Compiler/CompilerFactory.cs
  src/AppModel/NetDaemon.AppModel/Internal/Compiler/ICompilerFactory.cs
Labels: pr: new-feature

#638 Fix dev docs to point to netdaemon.xyz instead
  DEV.md
Labels: pr: enhancement

#639 Clean up unused files in Docker folder
  Docker/README.md
  Docker/build_dotnet.sh
  Docker/docker-compose.yml
Labels: pr: enhancement

#642 Update admin build process
  Dockerfile
Labels: pr: enhancement

#640 Bash lint/cleanup
  Docker/rootfs/etc/services.d/NetDaemonAddOnApp/run
  Docker/rootfs/etc/services.d/NetDaemonAdmin/run
  Docker/rootfs/etc/services.d/NetDaemonApp/run
  Docker/s6.sh
  Dockerfile
  Dockerfile.AddOn
Labels: pr: enhancement

#641 Testbuild the add-on container
  .github/workflows/test_docker.yml
Labels: pr: enhancement

#624 DisposableScheduler
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/Scheduling/CronTests.cs
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/Scheduling/DisposableSchedulerTest.cs
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/Scheduling/FakeLocalTimeZone.cs
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/Scheduling/SchedulingTests.cs
  src/Extensions/NetDaemon.Extensions.Scheduling/CronExtensions.cs
  src/Extensions/NetDaemon.Extensions.Scheduling/DependencyInjectionSetup.cs
  src/Extensions/NetDaemon.Extensions.Scheduling/DisposableScheduler.cs
  src/Extensions/NetDaemon.Extensions.Scheduling/NetDaemon.Extensions.Scheduling.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling/SchedulerExtensions.cs
Labels: pr: new-feature

#644 feat: introduce app instance factory to allow extending app instantiation logic
  src/AppModel/NetDaemon.AppModel.Tests/AppAssemblyProviders/CombinedAppAssemblyProviderTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/AppAssemblyProviders/DynamicAppAssemblyProviderTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/AppAssemblyProviders/LocalAppAssemblyProviderTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/AppFactories/DynamicAppFactoryTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/AppFactories/LocalAppFactoryTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/AppFactoryProviders/CombinedAppFactoryProviderTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/AppFactoryProviders/DynamicAppFactoryProviderTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/AppFactoryProviders/LocalAppFactoryProviderTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/AppModelTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/AssemblyResolver/AssemblyResolverTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/Context/ApplicationScopeTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/Fixtures/Local/LocalApp.cs
  src/AppModel/NetDaemon.AppModel.Tests/Fixtures/Local/LocalAppWithId.cs
  src/AppModel/NetDaemon.AppModel.Tests/Helpers/FakeOptionsExtensions.cs
  src/AppModel/NetDaemon.AppModel.Tests/TypeResolver/TypeResolverTests.cs
  src/AppModel/NetDaemon.AppModel/Common/Extensions/ServiceCollectionExtension.cs
  src/AppModel/NetDaemon.AppModel/GlobalUsings.cs
  src/AppModel/NetDaemon.AppModel/Internal/AppAssemblyProviders/AppAssemblyProvider.cs
  src/AppModel/NetDaemon.AppModel/Internal/AppAssemblyProviders/DynamicallyCompiledAppAssemblyProvider.cs
  src/AppModel/NetDaemon.AppModel/Internal/AppAssemblyProviders/IAppAssemblyProvider.cs
  src/AppModel/NetDaemon.AppModel/Internal/AppFactories/FuncAppFactory.cs
  src/AppModel/NetDaemon.AppModel/Internal/AppFactories/IAppFactory.cs
  src/AppModel/NetDaemon.AppModel/Internal/AppFactoryProviders/AssemblyAppFactoryProvider.cs
  src/AppModel/NetDaemon.AppModel/Internal/AppFactoryProviders/FuncAppFactoryProvider.cs
  src/AppModel/NetDaemon.AppModel/Internal/AppFactoryProviders/IAppFactoryProvider.cs
  src/AppModel/NetDaemon.AppModel/Internal/AppFactoryProviders/SingleAppFactoryProvider.cs
  src/AppModel/NetDaemon.AppModel/Internal/AppModelContext.cs
  src/AppModel/NetDaemon.AppModel/Internal/Application.cs
  src/AppModel/NetDaemon.AppModel/Internal/AssemblyResolver/IAssemblyResolver.cs
  src/AppModel/NetDaemon.AppModel/Internal/Context/ApplicationContext.cs
  src/AppModel/NetDaemon.AppModel/Internal/TypeResolver/AppTypeResolver.cs
  src/AppModel/NetDaemon.AppModel/Internal/TypeResolver/IAppTypeResolver.cs
  src/AppModel/NetDaemon.AppModel/Internal/TypeResolver/SingleAppResolver.cs
  src/Runtime/NetDaemon.Runtime.Tests/Integration/TestRuntime.cs
Labels: pr: enhancement

#643 Remove standard values for environment vars in docker file
  Dockerfile
Labels: pr: bugfix

#646 Loads HassModel.Integration the proper way
  dev/DebugHost/DebugHost.csproj
  src/Host/NetDaemon.Host.Default/Program.cs
Labels: pr: bugfix

#647 RenameAppMOdelAddMethods
  src/AppModel/NetDaemon.AppModel.Tests/AppFactories/LocalAppFactoryTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/AppFactoryProviders/CombinedAppFactoryProviderTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/AppFactoryProviders/LocalAppFactoryProviderTests.cs
  src/AppModel/NetDaemon.AppModel/Common/Extensions/ServiceCollectionExtension.cs
  src/Runtime/NetDaemon.Runtime.Tests/Integration/TestRuntime.cs
Labels: pr: enhancement
