Repository net-daemon/netdaemon, pull requests merged in 2022-12, with the labels that each got.

#799 Fix multi dispose scheduler and timer
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/Scheduling/DisposableSchedulerTest.cs
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/Scheduling/DisposableTimerTest.cs
  src/Extensions/NetDaemon.Extensions.Scheduling/DisposableScheduler.cs
  src/Extensions/NetDaemon.Extensions.Scheduling/DisposableTimer.cs
Labels: pr: enhancement

#808 Fix CA1852 violations
  .github/workflows/ci_build.yml
  .linting/roslynator.ruleset
Labels: pr: enhancement

#767 Code gen merge previous and current metadata
  src/HassModel/NetDaemon.HassModel.CodeGenerator/AttributeTypeGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/AttributeTypeGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/EntitiesGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/ExtensionMethodsGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/Generator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/ServiceArguments.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/ServicesGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGenerationSettings.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Controller.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/EntitiesGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/EntitySet.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Generator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/HaRepositry.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/NamingHelper.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/SyntaxFactoryHelper.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/AttributeMetaDataGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ClrTypeJsonConverter.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/EntityDomainMetadata.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/EntityMetaDataGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/EntityMetaDataMerger.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Program.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/AttributeMetaDataGeneratorTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/CodeGeneratorTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/MetaDataMergerTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Entities/EntityExtensionsTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Entities/EntityTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Entities/EnumerableEntityExtensionsTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Entities/NumericEntityTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/GlobalUsings.cs
  src/HassModel/NetDaemon.HassModel.Tests/Integration/IntegrationHaContextExtensionsTests.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/AppScopedHaContextProviderTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/BackgroundTaskTrackerTests.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/EntityAreaCachTests.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/EntityStateCacheTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/QueuedObservabeTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/ScopedObservableTests.cs
  src/HassModel/NetDaemon.HassModel.Tests/ObservableExtensionsTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/ServiceTargetTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/StateObservableExtensionsTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/TestHelpers/Extensions.cs
  src/HassModel/NetDaemon.HassModel.Tests/TestHelpers/HassClient/HaContextMock.cs
  src/HassModel/NetDeamon.HassModel/Entities/EntityState.cs
  src/HassModel/NetDeamon.HassModel/NetDaemon.HassModel.csproj
Labels: pr: new-feature

#811 Runtime version 3.1 - prepare for .NET 7 release
  .github/workflows/push_docker_addon_manual.yml
  .github/workflows/push_docker_manual.yml
  .github/workflows/tags_docker.yml
  Dockerfile
  Dockerfile.AddOn
  src/AppModel/NetDaemon.AppModel.Tests/NetDaemon.AppModel.Tests.csproj
  src/AppModel/NetDaemon.AppModel/NetDaemon.AppModel.csproj
  src/Client/NetDaemon.HassClient.Debug/NetDaemon.HassClient.Debug.csproj
  src/Client/NetDaemon.HassClient.Tests/NetDaemon.HassClient.Tests.csproj
  src/Client/NetDaemon.HassClient/NetDaemon.Client.csproj
  src/Extensions/NetDaemon.Extensions.Logging/NetDaemon.Extensions.Logging.csproj
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/NetDaemon.Extensions.MqttEntityManager.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/NetDaemon.Extensions.Scheduling.Tests.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling/NetDaemon.Extensions.Scheduling.csproj
  src/Extensions/NetDaemon.Extensions.Tts/NetDaemon.Extensions.Tts.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/Host/NetDaemon.Host.Default/NetDaemon.Host.Default.csproj
  src/Runtime/NetDaemon.Runtime.Tests/NetDaemon.Runtime.Tests.csproj
  src/Runtime/NetDaemon.Runtime/NetDaemon.Runtime.csproj
  src/debug/DebugHost/DebugHost.csproj
Labels: pr: dependency-update

#812 Fix docker push to wrong image
  .github/workflows/tags_docker.yml
Labels: pr: bugfix

#813 Fix #728 where extension methods were generated for typed entity clas…
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/ExtensionMethodsGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/SyntaxFactoryHelper.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Model/HassService.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Model/HassServiceDomain.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/CodeGenTestHelper.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/CodeGeneratorTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/ServicesGeneratorTest.cs
Labels: pr: bugfix

#816 Fix #815, TaskCanceledException when calling service from Dispose(Async)
  src/Client/NetDaemon.HassClient/Internal/HomeAssistantConnection.cs
Labels: pr: bugfix

#819 Refactor code generator and fix issue with services with multiple target domains
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/AttributeTypeGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/EntitiesGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/ExtensionMethodsGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/Generator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/ServiceArguments.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/ServicesGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/SyntaxFactoryHelper.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Controller.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/HassServiceArgumentMapper.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/NamingHelper.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/SyntaxFactoryHelper.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/TriviaHelper.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/EntityMetaData/AttributeMetaDataGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/EntityMetaData/ClrTypeJsonConverter.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/EntityMetaData/EntityDomainMetadata.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/EntityMetaData/EntityMetaDataGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/EntityMetaData/EntityMetaDataMerger.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ServicesMetaData/HassService.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ServicesMetaData/HassServiceArgumentMapper.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ServicesMetaData/HassServiceDomain.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ServicesMetaData/HassServiceField.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ServicesMetaData/SelectorConverter.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ServicesMetaData/Selectors.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ServicesMetaData/ServiceMetaDataParser.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ServicesMetaData/SnakeCaseNamingPolicy.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ServicesMetaData/StringAsArrayConverter.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Model/HassService.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Model/HassServiceField.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Model/JsonExtensions.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Model/NullableEnumStringConverter.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/CodeGenTestHelper.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/CodeGeneratorTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/ServiceMetaDataParserTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/ServicesGeneratorTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
Labels: pr: enhancement, pr: bugfix

#823 #698 Load codegen settings from UserSecrets if available
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Program.cs
Labels: pr: new-feature

#822 Fix #715, ProximityEntity with numeric state
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/EntityIdHelper.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/CodeGeneratorTest.cs
Labels: pr: enhancement
