Repository net-daemon/netdaemon, pull requests merged in 2023-07, with the labels that each got.

#889 Remove integration tests from default solution
  .vscode/settings.json
  NetDaemon.sln
  src/AppModel/NetDaemon.AppModel.Tests/NetDaemon.AppModel.Tests.csproj
  src/Client/NetDaemon.HassClient.Tests/NetDaemon.HassClient.Tests.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/NetDaemon.Extensions.Scheduling.Tests.csproj
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/Runtime/NetDaemon.Runtime.Tests/NetDaemon.Runtime.Tests.csproj
Labels: pr: enhancement

#893 Use testcontainers for integration tests
  .github/workflows/ci_build.yml
  .github/workflows/ci_integration_tests.yaml
  NetDaemon.sln
  src/AppModel/NetDaemon.AppModel.Tests/NetDaemon.AppModel.Tests.csproj
  src/Client/NetDaemon.HassClient.Tests/NetDaemon.HassClient.Tests.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/NetDaemon.Extensions.Scheduling.Tests.csproj
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/Runtime/NetDaemon.Runtime.Tests/NetDaemon.Runtime.Tests.csproj
  tests/Integration/NetDaemon.Tests.Integration/BasicTest.cs
  tests/Integration/NetDaemon.Tests.Integration/CodegenIntegrationTests.cs
  tests/Integration/NetDaemon.Tests.Integration/HA/config/automations.yaml
  tests/Integration/NetDaemon.Tests.Integration/HA/config/configuration.yaml
  tests/Integration/NetDaemon.Tests.Integration/HA/config/groups.yaml
  tests/Integration/NetDaemon.Tests.Integration/HA/config/scenes.yaml
  tests/Integration/NetDaemon.Tests.Integration/HA/config/scripts.yaml
  tests/Integration/NetDaemon.Tests.Integration/HA/config/secrets.yaml
  tests/Integration/NetDaemon.Tests.Integration/HA/docker-compose.yaml
  tests/Integration/NetDaemon.Tests.Integration/Helpers/HomeAssistantCollection.cs
  tests/Integration/NetDaemon.Tests.Integration/Helpers/HomeAssistantLifetime.cs
  tests/Integration/NetDaemon.Tests.Integration/Helpers/HomeAssistantTestContainer/HomeAssistantConfiguration.cs
  tests/Integration/NetDaemon.Tests.Integration/Helpers/HomeAssistantTestContainer/HomeAssistantContainer.cs
  tests/Integration/NetDaemon.Tests.Integration/Helpers/HomeAssistantTestContainer/HomeAssistantContainerBuilder.cs
  tests/Integration/NetDaemon.Tests.Integration/Helpers/NetDaemonIntegrationBase.cs
  tests/Integration/NetDaemon.Tests.Integration/Helpers/TestFixture.cs
  tests/Integration/NetDaemon.Tests.Integration/NetDaemon.Tests.Integration.csproj
  tests/Integration/NetDaemon.Tests.Integration/Startup.cs
Labels: pr: enhancement

#894 Dependency upgrades
  src/AppModel/NetDaemon.AppModel.Tests/NetDaemon.AppModel.Tests.csproj
  src/Client/NetDaemon.HassClient.Tests/Net/WebSocketTransportPipelineTests.cs
  src/Client/NetDaemon.HassClient.Tests/NetDaemon.HassClient.Tests.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/NetDaemon.Extensions.Scheduling.Tests.csproj
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/Runtime/NetDaemon.Runtime.Tests/NetDaemon.Runtime.Tests.csproj
  tests/Integration/NetDaemon.Tests.Integration/NetDaemon.Tests.Integration.csproj
Labels: pr: dependency-update

#895 Support calling services with return value
  src/Client/NetDaemon.HassClient.Tests/Integration/HomeAssistantServerMock.cs
  src/Client/NetDaemon.HassClient.Tests/Integration/Testdata/result_calendar_list_event.json
  src/Client/NetDaemon.HassClient.Tests/Integration/WebsocketIntegrationTests.cs
  src/Client/NetDaemon.HassClient/Common/HomeAssistant/Extensions/IHomeAssistantConnectionExtensions.cs
  src/Client/NetDaemon.HassClient/Common/HomeAssistant/Model/HassServiceResult.cs
  src/Client/NetDaemon.HassClient/Internal/HomeAssistant/Commands/CallExecuteScriptCommand.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/AppScopedHaContextProviderTest.cs
  src/HassModel/NetDeamon.HassModel/IHaContext.cs
  src/HassModel/NetDeamon.HassModel/Internal/AppScopedHaContextProvider.cs
  src/debug/DebugHost/apps/Client/ClientDebug.cs
  src/debug/DebugHost/apps/ServiceCall/ServiceApp.cs
  tests/Integration/HA/config/automations.yaml
  tests/Integration/HA/config/configuration.yaml
  tests/Integration/HA/config/scenes.yaml
  tests/Integration/HA/config/scripts.yaml
  tests/Integration/HA/config/secrets.yaml
  tests/Integration/HA/docker-compose.yaml
  tests/Integration/NetDaemon.Tests.Integration/CalendarTests.cs
  tests/Integration/NetDaemon.Tests.Integration/Helpers/HomeAssistantLifetime.cs
  tests/Integration/NetDaemon.Tests.Integration/Helpers/HomeAssistantTestContainer/HomeAssistantContainer.cs
Labels: pr: new-feature
