Repository net-daemon/netdaemon, pull requests merged in 2023-11, with the labels that each got.

#983 Fix CodeGen ServiceMetaDataParser, handle "step":"any"
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ServicesMetaData/Selectors.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ServicesMetaData/ServiceMetaDataParser.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/ServiceMetaDataParserTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/ServicesGeneratorTest.cs
  tests/Integration/NetDaemon.Tests.Integration/CodegenIntegrationTests.cs
Labels: pr: bugfix

#984 [Codegen] Allow any nullable double fields to be strings or doubles and improved error reporting
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Controller.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ServicesMetaData/SelectorConverter.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ServicesMetaData/Selectors.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ServicesMetaData/ServiceMetaDataParser.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ServicesMetaData/StringAsDoubleConverter.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/ServiceMetaDataParserTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/ServicesGeneratorTest.cs
Labels: pr: enhancement

#989 dependency updates
  src/AppModel/NetDaemon.AppModel.SourceDeployedApps/NetDaemon.AppModel.SourceDeployedApps.csproj
  src/AppModel/NetDaemon.AppModel.Tests/NetDaemon.AppModel.Tests.csproj
  src/AppModel/NetDaemon.AppModel/NetDaemon.AppModel.csproj
  src/Client/NetDaemon.HassClient.Debug/NetDaemon.HassClient.Debug.csproj
  src/Client/NetDaemon.HassClient.Tests/NetDaemon.HassClient.Tests.csproj
  src/Client/NetDaemon.HassClient/NetDaemon.Client.csproj
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/NetDaemon.Extensions.MqttEntityManager.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/NetDaemon.Extensions.Scheduling.Tests.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling/NetDaemon.Extensions.Scheduling.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDaemon.HassModel.Integration/NetDaemon.HassModel.Integration.csproj
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/HassModel/NetDeamon.HassModel/NetDaemon.HassModel.csproj
  src/Runtime/NetDaemon.Runtime.Tests/NetDaemon.Runtime.Tests.csproj
  src/Runtime/NetDaemon.Runtime/NetDaemon.Runtime.csproj
  tests/Integration/NetDaemon.Tests.Integration/NetDaemon.Tests.Integration.csproj
Labels: pr: dependency-update

#992 Handle and log exceptions during initialization after (re)connect to Home Assistant
  src/Runtime/NetDaemon.Runtime.Tests/Internal/NetDaemonRuntimeTests.cs
  src/Runtime/NetDaemon.Runtime/Internal/NetDaemonRuntime.cs
Labels: pr: bugfix

#998 Release .NET 8!
  src/AppModel/NetDaemon.AppModel.SourceDeployedApps/NetDaemon.AppModel.SourceDeployedApps.csproj
  src/AppModel/NetDaemon.AppModel.Tests/NetDaemon.AppModel.Tests.csproj
  src/AppModel/NetDaemon.AppModel/NetDaemon.AppModel.csproj
  src/Client/NetDaemon.HassClient.Debug/NetDaemon.HassClient.Debug.csproj
  src/Client/NetDaemon.HassClient.Tests/NetDaemon.HassClient.Tests.csproj
  src/Client/NetDaemon.HassClient/NetDaemon.Client.csproj
  src/Extensions/NetDaemon.Extensions.Logging/NetDaemon.Extensions.Logging.csproj
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/NetDaemon.Extensions.MqttEntityManager.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/NetDaemon.Extensions.Scheduling.Tests.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling/NetDaemon.Extensions.Scheduling.csproj
  src/Extensions/NetDaemon.Extensions.Tts/NetDaemon.Extensions.Tts.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDaemon.HassModel.Integration/NetDaemon.HassModel.Integration.csproj
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/HassModel/NetDeamon.HassModel/NetDaemon.HassModel.csproj
  src/Host/NetDaemon.Host.Default/NetDaemon.Host.Default.csproj
  src/Runtime/NetDaemon.Runtime.Tests/NetDaemon.Runtime.Tests.csproj
  src/Runtime/NetDaemon.Runtime/NetDaemon.Runtime.csproj
  tests/Integration/NetDaemon.Tests.Integration/NetDaemon.Tests.Integration.csproj
Labels: pr: dependency-update

#1001 Log correct json content of messages sent to HA on failed commands
  src/Client/NetDaemon.HassClient.Tests/HelperTest/ResultMessageHandlerTests.cs
  src/Client/NetDaemon.HassClient.Tests/NetDaemon.HassClient.Tests.csproj
  src/Client/NetDaemon.HassClient/Common/HomeAssistant/Model/CommandMessage.cs
  src/Client/NetDaemon.HassClient/Internal/Helpers/ResultMessageHandler.cs
  src/Client/NetDaemon.HassClient/Internal/HomeAssistantConnection.cs
Labels: pr: enhancement, pr: bugfix

#1004 Avoid logging critical error on reconnect when not needed
  src/Runtime/NetDaemon.Runtime.Tests/Internal/NetDaemonRuntimeTests.cs
  src/Runtime/NetDaemon.Runtime/Internal/NetDaemonRuntime.cs
Labels: pr: bugfix

#1006 Fix hardcoded path for add-on
  Docker/rootfs/etc/services.d/netdaemon_addon/run
Labels: pr: bugfix

#1013 Update some packages
  src/AppModel/NetDaemon.AppModel.SourceDeployedApps/NetDaemon.AppModel.SourceDeployedApps.csproj
  src/AppModel/NetDaemon.AppModel.Tests/NetDaemon.AppModel.Tests.csproj
  src/AppModel/NetDaemon.AppModel/NetDaemon.AppModel.csproj
  src/Client/NetDaemon.HassClient.Tests/NetDaemon.HassClient.Tests.csproj
  src/Client/NetDaemon.HassClient/NetDaemon.Client.csproj
  src/Extensions/NetDaemon.Extensions.Logging/NetDaemon.Extensions.Logging.csproj
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/NetDaemon.Extensions.MqttEntityManager.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/NetDaemon.Extensions.Scheduling.Tests.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling/NetDaemon.Extensions.Scheduling.csproj
  src/Extensions/NetDaemon.Extensions.Tts/NetDaemon.Extensions.Tts.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDaemon.HassModel.Integration/NetDaemon.HassModel.Integration.csproj
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/HassModel/NetDeamon.HassModel/NetDaemon.HassModel.csproj
  src/Runtime/NetDaemon.Runtime.Tests/NetDaemon.Runtime.Tests.csproj
  src/Runtime/NetDaemon.Runtime/NetDaemon.Runtime.csproj
  tests/Integration/NetDaemon.Tests.Integration/NetDaemon.Tests.Integration.csproj
Labels: pr: dependency-update
