Repository net-daemon/netdaemon, pull requests merged in 2023-03, with the labels that each got.

#851 ServiceMetaDataParser `bool? Required` string deserialization
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/EntityMetaData/NullableBoolJsonConverter.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ServicesMetaData/HassServiceField.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ServicesMetaData/ServiceMetaDataParser.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/ServiceMetaDataParserTest.cs
Labels: pr: bugfix

#852 MeansImplicitUse for NetDaemonAppAttribute
  src/AppModel/NetDaemon.AppModel/Common/Attributes/JetBrainsCodeAnnotations.cs
  src/AppModel/NetDaemon.AppModel/Common/Attributes/NetDaemonAppAttribute.cs
Labels: pr: enhancement

#855 Dependecy updates
  src/AppModel/NetDaemon.AppModel/NetDaemon.AppModel.csproj
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/NetDaemon.Extensions.MqttEntityManager.csproj
  src/Runtime/NetDaemon.Runtime/NetDaemon.Runtime.csproj
  tests/Integration/NetDaemon.Tests.Integration/NetDaemon.Tests.Integration.csproj
Labels: pr: dependency-update
