Repository net-daemon/netdaemon, pull requests merged in 2023-10, with the labels that each got.

#945 Validate version of nugets and nd-codegen match
  src/HassModel/NetDaemon.HassModel.CodeGenerator/DependencyValidator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/VersionHelper.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Program.cs
Labels: pr: enhancement

#946 Fix flaky internal integration test
  src/Client/NetDaemon.HassClient.Tests/Integration/HomeAssistantServerMock.cs
Labels: pr: bugfix

#951 Dependency upgrades
  src/AppModel/NetDaemon.AppModel.Tests/NetDaemon.AppModel.Tests.csproj
  src/AppModel/NetDaemon.AppModel/NetDaemon.AppModel.csproj
  src/Client/NetDaemon.HassClient.Tests/NetDaemon.HassClient.Tests.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/NetDaemon.Extensions.Scheduling.Tests.csproj
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/HassModel/NetDeamon.HassModel/Entities/EntityState.cs
  src/HassModel/NetDeamon.HassModel/IHaContext.cs
  src/HassModel/NetDeamon.HassModel/Internal/FormatHelpers.cs
  src/Runtime/NetDaemon.Runtime.Tests/NetDaemon.Runtime.Tests.csproj
  src/debug/MyNDApp/MyNDApp.csproj
  tests/Integration/NetDaemon.Tests.Integration/NetDaemon.Tests.Integration.csproj
Labels: pr: dependency-update

#955 Enable analyzers and add a editorconfig
  .editorconfig
  Directory.Build.props
  NetDaemon.sln
  src/AppModel/NetDaemon.AppModel.Tests/.editorconfig
  src/Client/NetDaemon.HassClient.Tests/.editorconfig
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/.editorconfig
  src/HassModel/NetDaemon.HassModel.Tests/.editorconfig
  src/Runtime/NetDaemon.Runtime.Tests/.editorconfig
  tests/Integration/NetDaemon.Tests.Integration/.editorconfig
Labels: pr: enhancement

#961 Better handling of faulty unloading of appa
  src/AppModel/NetDaemon.AppModel.Tests/AppModelTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/Fixtures/Local/AppThatTakesASlowTimeToDispose.cs
  src/AppModel/NetDaemon.AppModel.Tests/Helpers/TestHelpers.cs
  src/AppModel/NetDaemon.AppModel/Internal/AppModelContext.cs
  src/AppModel/NetDaemon.AppModel/Internal/Application.cs
  src/Runtime/NetDaemon.Runtime/Internal/NetDaemonRuntime.cs
  src/debug/DebugHost/apps/HelloApp/HelloApp.cs
Labels: pr: bugfix

#962 Set CurrentConnection to null before submitting OnDisconnected event
  src/Client/NetDaemon.HassClient.Tests/HelperTest/ResultMessageHandlerTests.cs
  src/Client/NetDaemon.HassClient.Tests/HomeAssistantRunnerTest/HomeAssistantRunnerTests.cs
  src/Client/NetDaemon.HassClient/Internal/HomeAssistantRunner.cs
Labels: pr: bugfix

#978 Move commonly used values for properties to the Directory.Build.props file
  .github/workflows/ci_analyze.yml
  .github/workflows/ci_build.yml
  .github/workflows/test_docker.yml
  Directory.Build.props
  Dockerfile
  Dockerfile.AddOn
  src/AppModel/NetDaemon.AppModel.SourceDeployedApps/NetDaemon.AppModel.SourceDeployedApps.csproj
  src/AppModel/NetDaemon.AppModel.Tests/NetDaemon.AppModel.Tests.csproj
  src/AppModel/NetDaemon.AppModel/NetDaemon.AppModel.csproj
  src/Client/NetDaemon.HassClient.Debug/NetDaemon.HassClient.Debug.csproj
  src/Client/NetDaemon.HassClient.Tests/NetDaemon.HassClient.Tests.csproj
  src/Client/NetDaemon.HassClient/NetDaemon.Client.csproj
  src/Extensions/NetDaemon.Extensions.Logging/NetDaemon.Extensions.Logging.csproj
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/NetDaemon.Extensions.MqttEntityManager.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/NetDaemon.Extensions.Scheduling.Tests.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling/NetDaemon.Extensions.Scheduling.csproj
  src/Extensions/NetDaemon.Extensions.Tts/NetDaemon.Extensions.Tts.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDaemon.HassModel.Integration/NetDaemon.HassModel.Integration.csproj
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/HassModel/NetDeamon.HassModel/NetDaemon.HassModel.csproj
  src/Host/NetDaemon.Host.Default/NetDaemon.Host.Default.csproj
  src/Runtime/NetDaemon.Runtime.Tests/NetDaemon.Runtime.Tests.csproj
  src/Runtime/NetDaemon.Runtime/NetDaemon.Runtime.csproj
  src/debug/DebugHost/DebugHost.csproj
  src/debug/DebugWebHost/DebugWebHost.csproj
  src/debug/MyLibrary/MyLibrary.csproj
  tests/Integration/NetDaemon.Tests.Integration/NetDaemon.Tests.Integration.csproj
Labels: enhancement, pr: enhancement

#979 Refactors
  .editorconfig
  src/AppModel/NetDaemon.AppModel/Internal/AppAssemblyProviders/IAppAssemblyProvider.cs
  src/AppModel/NetDaemon.AppModel/Internal/Context/ApplicationContext.cs
  src/Client/NetDaemon.HassClient.Tests/HelperTest/ResultMessageHandlerTests.cs
  src/Client/NetDaemon.HassClient/Common/Exceptions/HomeAssistantApiCallException.cs
  src/Client/NetDaemon.HassClient/Internal/Helpers/ResultMessageHandler.cs
  src/Client/NetDaemon.HassClient/Internal/HomeAssistantClient.cs
  src/Client/NetDaemon.HassClient/Internal/HomeAssistantConnection.cs
  src/Client/NetDaemon.HassClient/Internal/HomeAssistantConnectionFactory.cs
  src/Client/NetDaemon.HassClient/Internal/HomeAssistantRunner.cs
  src/Client/NetDaemon.HassClient/Internal/Net/WebSocketClientImpl.cs
  src/Client/NetDaemon.HassClient/Internal/Net/WebSocketTransportPipeline.cs
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/Scheduling/CronTests.cs
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/Scheduling/SchedulingTests.cs
  src/Runtime/NetDaemon.Runtime/Internal/AppStateManager.cs
  src/Runtime/NetDaemon.Runtime/Internal/AppStateRepository.cs
  src/Runtime/NetDaemon.Runtime/Internal/NetDaemonRuntime.cs
  src/Runtime/NetDaemon.Runtime/Internal/RuntimeService.cs
Labels: pr: enhancement

#980 On release created now activates a pre-release push to docker and nuget
  .github/workflows/tags_release_created.yml
Labels: pr: enhancement
