Repository net-daemon/netdaemon, pull requests merged in 2023-02, with the labels that each got.

#832 Prevent duplicate C# names after normalizing EntitiyIds
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/EntitiesGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/ServiceArguments.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Extensions/StringExtensions.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/NamingHelper.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/EntityMetaData/AttributeMetaDataGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/EntityMetaData/EntityDomainMetadata.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/EntityMetaData/EntityMetaDataGenerator.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/CodeGeneratorTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/MetaDataMergerTest.cs
Labels: pr: bugfix

#828 Add option to specify Cron Job with Seconds
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/Scheduling/CronTests.cs
  src/Extensions/NetDaemon.Extensions.Scheduling/CronExtensions.cs
Labels: pr: new-feature

#835 Correct names
  src/HassModel/NetDeamon.HassModel/StateObservableExtensions.cs
Labels: pr: enhancement

#838 Rename LICENCE to LICENSE
  LICENSE
Labels: pr: enhancement

#837 Encode characters to prevent invalid XML comments
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/SyntaxFactoryHelper.cs
Labels: pr: bugfix

#844 Xml comment grammar fixes & documentation improvements
  src/Client/NetDaemon.HassClient/Common/HomeAssistant/Extensions/IHomeAssistantConnectionExtensions.cs
  src/Client/NetDaemon.HassClient/Common/HomeAssistant/Model/Targets.cs
  src/Client/NetDaemon.HassClient/Common/Settings/Settings.cs
  src/HassModel/NetDaemon.HassModel.Integration/IntegrationHaContextExtensions.cs
  src/HassModel/NetDeamon.HassModel/Entities/Entity.cs
  src/HassModel/NetDeamon.HassModel/Entities/EntityExtensions.cs
  src/HassModel/NetDeamon.HassModel/Entities/EnumerableEntityExtensions.cs
  src/HassModel/NetDeamon.HassModel/Event.cs
  src/HassModel/NetDeamon.HassModel/IHaContext.cs
  src/HassModel/NetDeamon.HassModel/Internal/AppScopedHaContextProvider.cs
  src/HassModel/NetDeamon.HassModel/ServiceTarget.cs
Labels: pr: enhancement

#843 Use doubles instead of integers in the attribute base classes
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/CodeGeneratorTest.cs
  src/HassModel/NetDeamon.HassModel/Entities/Core/LightAttributesBase.cs
  src/HassModel/NetDeamon.HassModel/Entities/Core/MediaPlayerAttributesBase.cs
Labels: pr: enhancement

#847 Maintainence
  Dockerfile
  Dockerfile.AddOn
  NetDaemon.sln
  src/AppModel/NetDaemon.AppModel.Tests/NetDaemon.AppModel.Tests.csproj
  src/AppModel/NetDaemon.AppModel/NetDaemon.AppModel.csproj
  src/Client/NetDaemon.HassClient.Debug/NetDaemon.HassClient.Debug.csproj
  src/Client/NetDaemon.HassClient.Tests/NetDaemon.HassClient.Tests.csproj
  src/Extensions/NetDaemon.Extensions.Logging/NetDaemon.Extensions.Logging.csproj
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/NetDaemon.Extensions.MqttEntityManager.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/NetDaemon.Extensions.Scheduling.Tests.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling/NetDaemon.Extensions.Scheduling.csproj
  src/Extensions/NetDaemon.Extensions.Tts/NetDaemon.Extensions.Tts.csproj
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/HassModel/NetDeamon.HassModel/NetDaemon.HassModel.csproj
  src/Host/NetDaemon.Host.Default/NetDaemon.Host.Default.csproj
  src/Runtime/NetDaemon.Runtime.Tests/NetDaemon.Runtime.Tests.csproj
  src/Runtime/NetDaemon.Runtime/NetDaemon.Runtime.csproj
  src/debug/DebugHost/DebugHost.csproj
  tests/Integration/NetDaemon.Tests.Integration/NetDaemon.Tests.Integration.csproj
Labels: pr: dependency-update

#850 Dependecy upgrades
  src/AppModel/NetDaemon.AppModel.Tests/NetDaemon.AppModel.Tests.csproj
  src/AppModel/NetDaemon.AppModel/NetDaemon.AppModel.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/Runtime/NetDaemon.Runtime.Tests/NetDaemon.Runtime.Tests.csproj
Labels: pr: dependency-update
