Repository net-daemon/netdaemon, pull requests merged in 2023-08, with the labels that each got.

#898 Cleaned some extensions
  src/AppModel/NetDaemon.AppModel/Common/Extensions/IConfigurationBuilderExtensions.cs
  src/Runtime/NetDaemon.Runtime/Common/Extensions/HostBuilderExtensions.cs
Labels: pr: enhancement

#901 Add default metadata for lights entities
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Controller.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/DefaultMetadata/DefaultEntityMetaData.json
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/EntityMetaData/EntityMetaDataMerger.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/ControllerTest.cs
Labels: pr: enhancement

#903 Add media player to default meta
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/NamingHelper.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/DefaultMetadata/DefaultEntityMetaData.json
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/EntityMetaData/EntityMetaDataMerger.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/CodeGenTestHelper.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/ControllerTest.cs
  src/HassModel/NetDeamon.HassModel/Entities/Core/LightAttributesBase.cs
  src/HassModel/NetDeamon.HassModel/Entities/Core/MediaPlayerAttributesBase.cs
Labels: pr: enhancement

#904 Add version output to code generator
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/Generator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/VersionHelper.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Program.cs
Labels: pr: new-feature

#908 Generate docs for all packagable projects and resolved some issues
  .github/workflows/ci_build.yml
  src/AppModel/NetDaemon.AppModel/Common/Extensions/ServiceCollectionExtension.cs
  src/AppModel/NetDaemon.AppModel/NetDaemon.AppModel.csproj
  src/Client/NetDaemon.HassClient/Internal/HomeAssistantConnection.cs
  src/Client/NetDaemon.HassClient/NetDaemon.Client.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/ExtensionMethodsGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDaemon.HassModel.Integration/NetDaemon.HassModel.Integration.csproj
  src/HassModel/NetDeamon.HassModel/NetDaemon.HassModel.csproj
  src/Runtime/NetDaemon.Runtime/Internal/EntityMapperHelper.cs
  src/Runtime/NetDaemon.Runtime/NetDaemon.Runtime.csproj
Labels: pr: enhancement

#897 Add interfaces
  NetDaemon.sln
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/EntitiesGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/ExtensionMethodsGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/HelpersGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGenerationSettings.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/EntityMetaData/EntityDomainMetadata.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/CodeGeneratorTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/ServicesGeneratorTest.cs
  src/HassModel/NetDeamon.HassModel/Entities/Core/CoreInterfaces.cs
  src/HassModel/NetDeamon.HassModel/Entities/Core/IEntityCore.cs
  src/HassModel/NetDeamon.HassModel/Entities/Entity.cs
  src/HassModel/NetDeamon.HassModel/Entities/EntityExtensions.cs
  src/HassModel/NetDeamon.HassModel/Entities/EnumerableEntityExtensions.cs
  src/HassModel/NetDeamon.HassModel/Entities/NumericEntity.cs
  src/debug/MyLibrary/InternalHomeAssistantGenerated/LightEntityExtensionMethods.cs
  src/debug/MyLibrary/MyLibrary.csproj
  src/debug/MyLibrary/MyLibraryClass.cs
  src/debug/MyNDApp/.gitignore
  src/debug/MyNDApp/HomeAssistantGenerated.cs
  src/debug/MyNDApp/MyNDApp.csproj
  src/debug/MyNDApp/apps/HassModel/MyInterfaceAutomation/InterfaceUsage.cs
  src/debug/MyNDApp/program.cs
Labels: pr: new-feature

#913 Fix missing xml comments
  src/AppModel/NetDaemon.AppModel/Common/Attributes/JetBrainsCodeAnnotations.cs
  src/AppModel/NetDaemon.AppModel/Internal/AppAssemblyProviders/DynamicallyCompiledAppAssemblyProvider.cs
  src/AppModel/NetDaemon.AppModel/Internal/Compiler/CollectableAssemblyLoadContext.cs
  src/AppModel/NetDaemon.AppModel/Internal/Compiler/Compiler.cs
  src/AppModel/NetDaemon.AppModel/Internal/Config/Yaml/YamlConfigurationSource.cs
  src/AppModel/NetDaemon.AppModel/NetDaemon.AppModel.csproj
  src/Client/NetDaemon.HassClient/NetDaemon.Client.csproj
  src/Runtime/NetDaemon.Runtime/Common/Extensions/HostBuilderExtensions.cs
  src/Runtime/NetDaemon.Runtime/Common/Extensions/ServiceBuilderExtensions.cs
  src/Runtime/NetDaemon.Runtime/Common/Extensions/ServiceCollectionExtensions.cs
  src/Runtime/NetDaemon.Runtime/Common/IRuntime.cs
  src/Runtime/NetDaemon.Runtime/NetDaemon.Runtime.csproj
Labels: pr: enhancement

#916 Dependency upgrades
  src/AppModel/NetDaemon.AppModel.Tests/NetDaemon.AppModel.Tests.csproj
  src/AppModel/NetDaemon.AppModel/NetDaemon.AppModel.csproj
  src/Client/NetDaemon.HassClient.Tests/NetDaemon.HassClient.Tests.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/NetDaemon.Extensions.Scheduling.Tests.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/Runtime/NetDaemon.Runtime.Tests/NetDaemon.Runtime.Tests.csproj
  src/debug/MyNDApp/MyNDApp.csproj
  tests/Integration/NetDaemon.Tests.Integration/NetDaemon.Tests.Integration.csproj
Labels: pr: dependency-update

#924 Log how many applications where loaded and what state they are in
  src/AppModel/NetDaemon.AppModel/Internal/AppModelContext.cs
Labels: pr: enhancement

#929 Handle selector for Multiple entities (specifically for media_player.join
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ServicesMetaData/HassServiceArgumentMapper.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ServicesMetaData/Selectors.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/ServicesGeneratorTest.cs
Labels: pr: bugfix
