Repository net-daemon/netdaemon, pull requests merged in 2023-04, with the labels that each got.

#856 Added [NotNullWhen(true)] for Entity IsOn & IsOff extension methods
  src/HassModel/NetDeamon.HassModel/Entities/EntityExtensions.cs
Labels: pr: enhancement

#858 Handle changed service metadata json with multiple targets entities
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/ExtensionMethodsGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ServicesMetaData/Selectors.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ServicesMetaData/SingleObjectAsArrayConverter.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/CodeGeneratorTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/ServiceMetaDataParserTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/ServicesGeneratorTest.cs
Labels: pr: bugfix

#859 Adding code generation tests in the integration tests.
  src/HassModel/NetDaemon.HassModel.CodeGenerator/GlobalUsings.cs
  tests/Integration/NetDaemon.Tests.Integration/CodegenIntegrationTests.cs
  tests/Integration/NetDaemon.Tests.Integration/NetDaemon.Tests.Integration.csproj
Labels: pr: enhancement

#860 Prototype - Trigger subscriptions
  src/Client/NetDaemon.HassClient.Tests/Integration/HomeAssistantServerMock.cs
  src/Client/NetDaemon.HassClient/Common/HomeAssistant/Extensions/IHomeAssistantConnectionExtensions.cs
  src/Client/NetDaemon.HassClient/Common/HomeAssistant/Model/HassEvent.cs
  src/Client/NetDaemon.HassClient/Common/HomeAssistant/Model/HassVariable.cs
  src/Client/NetDaemon.HassClient/Common/IHomeAssistantConnection.cs
  src/Client/NetDaemon.HassClient/Internal/HomeAssistant/Commands/SubscribeTriggerCommand.cs
  src/Client/NetDaemon.HassClient/Internal/HomeAssistant/Commands/UnsubscribeEventsCommand.cs
  src/Client/NetDaemon.HassClient/Internal/HomeAssistantConnection.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/TriggerManagerTest.cs
  src/HassModel/NetDeamon.HassModel/DependencyInjectionSetup.cs
  src/HassModel/NetDeamon.HassModel/ITriggerManager.cs
  src/HassModel/NetDeamon.HassModel/Internal/TriggerManager.cs
  src/HassModel/NetDeamon.HassModel/TriggerManagerExtensions.cs
  src/debug/DebugHost/DebugHost.csproj
  src/debug/DebugHost/apps/Client/ClientDebug.cs
Labels: pr: new-feature

#862 Use IQueuedObservable in TriggerManager and update DI registration for this
  src/HassModel/NetDaemon.HassModel.Tests/Internal/TriggerManagerTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/TestHelpers/Extensions.cs
  src/HassModel/NetDeamon.HassModel/DependencyInjectionSetup.cs
  src/HassModel/NetDeamon.HassModel/Internal/TriggerManager.cs
Labels: pr: enhancement
