Repository net-daemon/netdaemon, pull requests merged in 2024-04, with the labels that each got.

#1078 Add support for labels and floors in HassClient
  src/Client/NetDaemon.HassClient.Tests/Integration/HomeAssistantServerMock.cs
  src/Client/NetDaemon.HassClient.Tests/Integration/Testdata/result_get_floors.json
  src/Client/NetDaemon.HassClient.Tests/Integration/Testdata/result_get_labels.json
  src/Client/NetDaemon.HassClient.Tests/Integration/WebsocketIntegrationTests.cs
  src/Client/NetDaemon.HassClient/Common/HomeAssistant/Extensions/IHomeAssistantConnectionExtensions.cs
  src/Client/NetDaemon.HassClient/Common/HomeAssistant/Model/HassFloor.cs
  src/Client/NetDaemon.HassClient/Common/HomeAssistant/Model/HassLabel.cs
  src/debug/DebugHost/apps/Client/LabelDebug.cs
Labels: pr: new-feature

#1076 Make AddScopedHaContext public
  src/HassModel/NetDeamon.HassModel/DependencyInjectionSetup.cs
Labels: pr: enhancement

#1082 Upgrade Nugets
  src/AppModel/NetDaemon.AppModel.SourceDeployedApps/NetDaemon.AppModel.SourceDeployedApps.csproj
  src/AppModel/NetDaemon.AppModel.Tests/NetDaemon.AppModel.Tests.csproj
  src/AppModel/NetDaemon.AppModel/NetDaemon.AppModel.csproj
  src/Client/NetDaemon.HassClient.Debug/NetDaemon.HassClient.Debug.csproj
  src/Client/NetDaemon.HassClient.Tests/NetDaemon.HassClient.Tests.csproj
  src/Client/NetDaemon.HassClient/NetDaemon.Client.csproj
  src/Extensions/NetDaemon.Extensions.Logging/NetDaemon.Extensions.Logging.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/NetDaemon.Extensions.Scheduling.Tests.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling/NetDaemon.Extensions.Scheduling.csproj
  src/Extensions/NetDaemon.Extensions.Tts/NetDaemon.Extensions.Tts.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/Host/NetDaemon.Host.Default/NetDaemon.Host.Default.csproj
  src/Runtime/NetDaemon.Runtime.Tests/NetDaemon.Runtime.Tests.csproj
  src/Runtime/NetDaemon.Runtime/NetDaemon.Runtime.csproj
  tests/Integration/NetDaemon.Tests.Integration/NetDaemon.Tests.Integration.csproj
Labels: pr: dependency-update

#1077 Alfa version of Registry object, work in progress
  src/Client/NetDaemon.HassClient/Common/HomeAssistant/Model/HassArea.cs
  src/Client/NetDaemon.HassClient/Common/HomeAssistant/Model/HassDevice.cs
  src/Client/NetDaemon.HassClient/Common/HomeAssistant/Model/HassEntity.cs
  src/Client/NetDaemon.HassClient/Common/HomeAssistant/Model/HassLabel.cs
  src/HassModel/NetDaemon.HassModel.Tests/Entities/EntityTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/EntityAreaCachTests.cs
  src/HassModel/NetDaemon.HassModel.Tests/Registry/RegistryNavigationTest.cs
  src/HassModel/NetDeamon.HassModel/DependencyInjectionSetup.cs
  src/HassModel/NetDeamon.HassModel/Entities/Area.cs
  src/HassModel/NetDeamon.HassModel/Entities/Entity.cs
  src/HassModel/NetDeamon.HassModel/HaRegistry.cs
  src/HassModel/NetDeamon.HassModel/IHaContext.cs
  src/HassModel/NetDeamon.HassModel/IHaRegistry.cs
  src/HassModel/NetDeamon.HassModel/IHaRegistryNavigator.cs
  src/HassModel/NetDeamon.HassModel/Internal/AppScopedHaContextProvider.cs
  src/HassModel/NetDeamon.HassModel/Internal/CacheManager.cs
  src/HassModel/NetDeamon.HassModel/Internal/EntityAreaCache.cs
  src/HassModel/NetDeamon.HassModel/Internal/HassObjectMapper.cs
  src/HassModel/NetDeamon.HassModel/Internal/RegistryCache.cs
  src/HassModel/NetDeamon.HassModel/Registry/Area.cs
  src/HassModel/NetDeamon.HassModel/Registry/Device.cs
  src/HassModel/NetDeamon.HassModel/Registry/EntityRegistration.cs
  src/HassModel/NetDeamon.HassModel/Registry/Floor.cs
  src/HassModel/NetDeamon.HassModel/Registry/Label.cs
  src/debug/DebugHost/apps/Client/ClientDebug.cs
  src/debug/DebugHost/apps/Client/LabelDebug.cs
  src/debug/DebugHost/apps/HelloApp/HelloApp.cs
  src/debug/DebugHost/apps/ServiceCall/ServiceApp.cs
  src/debug/DebugHost/apps_src/hellow.cs
Labels: pr: new-feature

#1084 Added support for floors and labels to the ServiceTarget class
  src/Client/NetDaemon.HassClient/Common/HomeAssistant/Model/Targets.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/AppScopedHaContextProviderTest.cs
  src/HassModel/NetDeamon.HassModel/Internal/HassObjectMapper.cs
  src/HassModel/NetDeamon.HassModel/ServiceTarget.cs
  src/debug/DebugHost/apps/Client/ClientDebug.cs
  src/debug/DebugHost/apps/Client/LabelDebug.cs
  src/debug/DebugHost/apps/Config/ConfigApp.cs
  src/debug/DebugHost/apps/HaRegistry/RegistryApp.cs
  src/debug/DebugHost/apps/HelloApp/HelloApp.cs
  src/debug/DebugHost/apps_src/hellow.cs
  src/debug/MyNDApp/apps/HassModel/MyInterfaceAutomation/InterfaceUsage.cs
Labels: pr: new-feature
