Repository net-daemon/netdaemon, pull requests merged in 2024-10, with the labels that each got.

#1188 Hassmodel APIs creates entities of types created by nd-codegen
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/EntityFactoryGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/Generator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/HelpersGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ServicesMetaData/HassServiceDomain.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/CodeGenTestHelper.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/EntityFactoryGeneratorTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/NetDaemonTestAppAttribute.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/ServicesGeneratorTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Registry/RegistryNavigationTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/TestHelpers/Extensions.cs
  src/HassModel/NetDeamon.HassModel/DependencyInjectionSetup.cs
  src/HassModel/NetDeamon.HassModel/Entities/DefaultEntityFactory.cs
  src/HassModel/NetDeamon.HassModel/Entities/StateChange.cs
  src/HassModel/NetDeamon.HassModel/HaContextExtensions.cs
  src/HassModel/NetDeamon.HassModel/IEntityFactory.cs
  src/HassModel/NetDeamon.HassModel/IHaContext.cs
  src/HassModel/NetDeamon.HassModel/Internal/AppScopedHaContextProvider.cs
  src/HassModel/NetDeamon.HassModel/Internal/HassObjectMapper.cs
  src/HassModel/NetDeamon.HassModel/NetDaemon.HassModel.csproj
  src/debug/DebugHost/apps/HelloApp/HelloApp.cs
Labels: pr: new-feature

#1189 Updating nuget packages
  src/AppModel/NetDaemon.AppModel.SourceDeployedApps/NetDaemon.AppModel.SourceDeployedApps.csproj
  src/AppModel/NetDaemon.AppModel.Tests/NetDaemon.AppModel.Tests.csproj
  src/AppModel/NetDaemon.AppModel/NetDaemon.AppModel.csproj
  src/Client/NetDaemon.HassClient.Debug/NetDaemon.HassClient.Debug.csproj
  src/Client/NetDaemon.HassClient.Tests/NetDaemon.HassClient.Tests.csproj
  src/Client/NetDaemon.HassClient/NetDaemon.Client.csproj
  src/Extensions/NetDaemon.Extensions.Logging/NetDaemon.Extensions.Logging.csproj
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/NetDaemon.Extensions.MqttEntityManager.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/NetDaemon.Extensions.Scheduling.Tests.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling/NetDaemon.Extensions.Scheduling.csproj
  src/Extensions/NetDaemon.Extensions.Tts/NetDaemon.Extensions.Tts.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/HassModel/NetDeamon.HassModel/NetDaemon.HassModel.csproj
  src/Host/NetDaemon.Host.Default/NetDaemon.Host.Default.csproj
  src/Runtime/NetDaemon.Runtime.Tests/NetDaemon.Runtime.Tests.csproj
  src/Runtime/NetDaemon.Runtime/NetDaemon.Runtime.csproj
  tests/Integration/NetDaemon.Tests.Integration/NetDaemon.Tests.Integration.csproj
Labels: pr: dependency-update

#1190 Fix #1166 Exception with Code generator when an attribute name has no alfanumeric characters
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/ServiceArguments.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Extensions/StringExtensions.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/CodeGeneratorTest.cs
Labels: pr: bugfix

#1191 Have nd-codegen check for available updates
  src/HassModel/NetDaemon.HassModel.CodeGenerator/DependencyValidator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/VersionHelper.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Program.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/DependencyValidatorTests.cs
Labels: pr: enhancement

#1193 Newest Nuget packages
  src/AppModel/NetDaemon.AppModel.SourceDeployedApps/NetDaemon.AppModel.SourceDeployedApps.csproj
  src/AppModel/NetDaemon.AppModel/NetDaemon.AppModel.csproj
  src/Client/NetDaemon.HassClient.Debug/NetDaemon.HassClient.Debug.csproj
  src/Client/NetDaemon.HassClient/NetDaemon.Client.csproj
  src/Extensions/NetDaemon.Extensions.Logging/NetDaemon.Extensions.Logging.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling/NetDaemon.Extensions.Scheduling.csproj
  src/Extensions/NetDaemon.Extensions.Tts/NetDaemon.Extensions.Tts.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/Host/NetDaemon.Host.Default/NetDaemon.Host.Default.csproj
  src/Runtime/NetDaemon.Runtime/NetDaemon.Runtime.csproj
Labels: pr: dependency-update
