Repository net-daemon/netdaemon, pull requests merged in 2024-01, with the labels that each got.

#1023 Add EnumerateAll() to generated Entities Classes
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/EntitiesGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/EnumerateAllGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Helpers/NamingHelper.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/CodeGeneratorTest.cs
Labels: pr: new-feature

#1032 Update latest nuget packages
  src/AppModel/NetDaemon.AppModel.SourceDeployedApps/NetDaemon.AppModel.SourceDeployedApps.csproj
  src/AppModel/NetDaemon.AppModel.Tests/NetDaemon.AppModel.Tests.csproj
  src/AppModel/NetDaemon.AppModel/NetDaemon.AppModel.csproj
  src/Client/NetDaemon.HassClient.Debug/NetDaemon.HassClient.Debug.csproj
  src/Client/NetDaemon.HassClient.Tests/NetDaemon.HassClient.Tests.csproj
  src/Client/NetDaemon.HassClient/NetDaemon.Client.csproj
  src/Extensions/NetDaemon.Extensions.Logging/NetDaemon.Extensions.Logging.csproj
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/NetDaemon.Extensions.MqttEntityManager.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/NetDaemon.Extensions.Scheduling.Tests.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling/NetDaemon.Extensions.Scheduling.csproj
  src/Extensions/NetDaemon.Extensions.Tts/NetDaemon.Extensions.Tts.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/Host/NetDaemon.Host.Default/NetDaemon.Host.Default.csproj
  src/Runtime/NetDaemon.Runtime.Tests/NetDaemon.Runtime.Tests.csproj
  src/Runtime/NetDaemon.Runtime/NetDaemon.Runtime.csproj
  tests/Integration/NetDaemon.Tests.Integration/NetDaemon.Tests.Integration.csproj
Labels: pr: dependency-update

#1035 Fix HA changed light attributes are all null iso missing for lights t…
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/AttributeTypeGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/EntityMetaData/AttributeMetaDataGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/EntityMetaData/ClrTypeJsonConverter.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/EntityMetaData/EntityDomainMetadata.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/EntityMetaData/EntityMetaDataMerger.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/AttributeMetaDataGeneratorTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/MetaDataMergerTest.cs
Labels: pr: enhancement
