Repository net-daemon/netdaemon, pull requests merged in 2024-12, with the labels that each got.

#1213 Upgrade Nugets
  src/AppModel/NetDaemon.AppModel.SourceDeployedApps/NetDaemon.AppModel.SourceDeployedApps.csproj
  src/AppModel/NetDaemon.AppModel.Tests/NetDaemon.AppModel.Tests.csproj
  src/AppModel/NetDaemon.AppModel/NetDaemon.AppModel.csproj
  src/Client/NetDaemon.HassClient.Tests/NetDaemon.HassClient.Tests.csproj
  src/Extensions/NetDaemon.Extensions.Logging/NetDaemon.Extensions.Logging.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/NetDaemon.Extensions.Scheduling.Tests.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling/NetDaemon.Extensions.Scheduling.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/Runtime/NetDaemon.Runtime.Tests/NetDaemon.Runtime.Tests.csproj
  tests/Integration/NetDaemon.Tests.Integration/NetDaemon.Tests.Integration.csproj
Labels: pr: dependency-update

#1217 Fix: Apps that were started from HA are not retsrated after a reconnect
  src/Runtime/NetDaemon.Runtime/Internal/AppStateManager.cs
Labels: pr: bugfix

#1218 Avoid Exceptions when AppConfigPath does not exist
  src/AppModel/NetDaemon.AppModel.SourceDeployedApps/Compiler/SyntaxTreeResolver.cs
  src/AppModel/NetDaemon.AppModel/Common/Extensions/IConfigurationBuilderExtensions.cs
  src/Runtime/NetDaemon.Runtime/Internal/NetDaemonRuntime.cs
Labels: pr: enhancement

#1220 Fix README
  README.md
Labels: pr: enhancement

#1224 Update GitHub workflow files
  .github/dependabot.yml
  .github/workflows/ci_analyze.yml
  .github/workflows/ci_build.yml
  .github/workflows/push_docker_addon_manual.yml
  .github/workflows/push_docker_manual.yml
  .github/workflows/push_docker_prerelease.yml
  .github/workflows/push_nuget_prerelease.yml
  .github/workflows/release_drafter.yml
  .github/workflows/tags_docker.yml
  .github/workflows/tags_nuget.yml
  .github/workflows/test_docker.yml
Labels: pr: enhancement
