Repository net-daemon/netdaemon, pull requests merged in 2024-09, with the labels that each got.

#1164 Handle decimals in JSON response
  src/Client/NetDaemon.HassClient.Tests/Json/EnsureStringConverterTests.cs
  src/Client/NetDaemon.HassClient/Internal/Json/EnsureStringConverter.cs
Labels: pr: enhancement

#1157 Properly deserialize context when deserializing state in the entity state cache
  src/HassModel/NetDaemon.HassModel.Tests/Internal/EntityStateCacheTest.cs
  src/HassModel/NetDeamon.HassModel/Context.cs
Labels: pr: bugfix

#1174 Upgrade Nuget packages
  src/AppModel/NetDaemon.AppModel.Tests/NetDaemon.AppModel.Tests.csproj
  src/Client/NetDaemon.HassClient.Tests/NetDaemon.HassClient.Tests.csproj
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/NetDaemon.Extensions.MqttEntityManager.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/NetDaemon.Extensions.Scheduling.Tests.csproj
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/Runtime/NetDaemon.Runtime.Tests/NetDaemon.Runtime.Tests.csproj
  tests/Integration/NetDaemon.Tests.Integration/NetDaemon.Tests.Integration.csproj
Labels: pr: dependency-update

#1167 Expose Entity Registration Conversation Options
  src/Client/NetDaemon.HassClient.Tests/Integration/Testdata/result_get_entities.json
  src/Client/NetDaemon.HassClient.Tests/Integration/WebsocketIntegrationTests.cs
  src/Client/NetDaemon.HassClient/Common/HomeAssistant/Model/HassConversationOptions.cs
  src/Client/NetDaemon.HassClient/Common/HomeAssistant/Model/HassEntity.cs
  src/Client/NetDaemon.HassClient/Common/HomeAssistant/Model/HassEntityOptions.cs
  src/HassModel/NetDaemon.HassModel.Tests/Registry/RegistryNavigationTest.cs
  src/HassModel/NetDeamon.HassModel/Internal/HassObjectMapper.cs
  src/HassModel/NetDeamon.HassModel/Registry/ConversationOptions.cs
  src/HassModel/NetDeamon.HassModel/Registry/EntityOptions.cs
  src/HassModel/NetDeamon.HassModel/Registry/EntityRegistration.cs
Labels: pr: enhancement

#1177 Remove constructors that take client types from public HassModel API
  src/HassModel/NetDeamon.HassModel/Internal/HassObjectMapper.cs
  src/HassModel/NetDeamon.HassModel/Registry/ConversationOptions.cs
  src/HassModel/NetDeamon.HassModel/Registry/EntityOptions.cs
Labels: pr: enhancement
