Repository net-daemon/netdaemon, pull requests merged in 2024-07, with the labels that each got.

#1129 Make restart logic progressive and other small fixes
  .github/workflows/push_nuget_prerelease.yml
  .github/workflows/tags_nuget.yml
  src/Client/NetDaemon.HassClient.Debug/Service.cs
  src/Client/NetDaemon.HassClient.Tests/HelperTest/ProgressiveTimoutTests.cs
  src/Client/NetDaemon.HassClient.Tests/HomeAssistantRunnerTest/HomeAssistantRunnerTests.cs
  src/Client/NetDaemon.HassClient/Internal/Helpers/ProgressiveTimeout.cs
  src/Client/NetDaemon.HassClient/Internal/HomeAssistantRunner.cs
  src/HassModel/NetDeamon.HassModel/Internal/RegistryCache.cs
  src/Runtime/NetDaemon.Runtime/Internal/NetDaemonRuntime.cs
Labels: pr: enhancement

#1131 Stability fixes
  src/AppModel/NetDaemon.AppModel.Tests/AppModelTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/Context/ApplicationContextTests.cs
  src/AppModel/NetDaemon.AppModel/Internal/AppModelContext.cs
  src/AppModel/NetDaemon.AppModel/Internal/Context/ApplicationContext.cs
  src/Client/NetDaemon.HassClient.Tests/HomeAssistantClientTest/HomeAssistantConnectionTests.cs
  src/Client/NetDaemon.HassClient/Internal/HomeAssistantConnection.cs
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/MessageSubscriber.cs
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/Scheduling/DisposableSchedulerTest.cs
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/Scheduling/DisposableTimerTest.cs
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/Scheduling/SchedulingTests.cs
  src/Extensions/NetDaemon.Extensions.Scheduling/DisposableScheduler.cs
  src/Extensions/NetDaemon.Extensions.Scheduling/DisposableTimer.cs
  src/Extensions/NetDaemon.Extensions.Scheduling/NetDaemonScheduler.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/AppScopedHaContextProviderTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/BackgroundTaskTrackerTests.cs
  src/HassModel/NetDeamon.HassModel/Internal/AppScopedHaContextProvider.cs
  src/HassModel/NetDeamon.HassModel/Internal/BackgroundTaskTracker.cs
  src/HassModel/NetDeamon.HassModel/Internal/IBackgroundTaskTracker.cs
  src/HassModel/NetDeamon.HassModel/Internal/QueuedObservable.cs
  src/Runtime/NetDaemon.Runtime/Internal/NetDaemonRuntime.cs
  src/debug/DebugHost/apps/ServiceCall/ServiceApp.cs
Labels: pr: enhancement, pr: bugfix

#1132 Codegen: Handel advanced_fields in Service metadata
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ServicesMetaData/ServiceMetaDataParser.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/ServiceMetaDataParserTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/ServiceMetaDataSamples/Lights.json
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
Labels: pr: dependency-update

#1134 Fix the WhenStateIsSame should not call action when completed
  src/HassModel/NetDaemon.HassModel.Tests/StateObservableExtensionsTest.cs
  src/HassModel/NetDeamon.HassModel/StateObservableExtensions.cs
Labels: pr: bugfix

#1135 Add extension function on observable to ignore OnComplete events
  src/HassModel/NetDaemon.HassModel.Tests/StateObservableExtensionsTest.cs
  src/HassModel/NetDeamon.HassModel/StateObservableExtensions.cs
Labels: pr: enhancement

#1140 Enable Apps to call services when app shuts down in Dispose(Async)() and OnComplete of HA events
  src/Client/NetDaemon.HassClient/Internal/HomeAssistantConnection.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/AppScopedHaContextProviderTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/QueuedObservabeTest.cs
  src/HassModel/NetDeamon.HassModel/DependencyInjectionSetup.cs
  src/HassModel/NetDeamon.HassModel/IQueuedObservable.cs
  src/HassModel/NetDeamon.HassModel/Internal/AppScopedHaContextProvider.cs
  src/HassModel/NetDeamon.HassModel/Internal/QueuedObservable.cs
  src/HassModel/NetDeamon.HassModel/Internal/TriggerManager.cs
  src/Runtime/NetDaemon.Runtime.Tests/Helpers/NonQueuedObservableMock.cs
Labels: pr: enhancement

#1139 Upgrade Nuget packages
  src/AppModel/NetDaemon.AppModel.SourceDeployedApps/NetDaemon.AppModel.SourceDeployedApps.csproj
  src/AppModel/NetDaemon.AppModel.Tests/NetDaemon.AppModel.Tests.csproj
  src/AppModel/NetDaemon.AppModel/NetDaemon.AppModel.csproj
  src/Client/NetDaemon.HassClient.Tests/NetDaemon.HassClient.Tests.csproj
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/NetDaemon.Extensions.MqttEntityManager.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/NetDaemon.Extensions.Scheduling.Tests.csproj
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/Runtime/NetDaemon.Runtime.Tests/NetDaemon.Runtime.Tests.csproj
  src/Runtime/NetDaemon.Runtime/NetDaemon.Runtime.csproj
  tests/Integration/NetDaemon.Tests.Integration/NetDaemon.Tests.Integration.csproj
Labels: pr: dependency-update

#1142 Make sure the registry cache is not refreshed more than once every 5 minutes
  src/HassModel/NetDaemon.HassModel.Tests/Internal/NetDaemonExtensionsTest.cs
  src/HassModel/NetDeamon.HassModel/Internal/ExtensionMethods.cs
  src/HassModel/NetDeamon.HassModel/Internal/RegistryCache.cs
Labels: pr: enhancement

#1143 Upgrade to latest version of ConfigurationBinder class as of .net 8
  src/AppModel/NetDaemon.AppModel.Tests/Config/ConfigurationBinderTests.cs
  src/AppModel/NetDaemon.AppModel.Tests/Config/Fixtures/CollectionTestsFixture.yaml
  src/AppModel/NetDaemon.AppModel/Internal/Config/BindingPoint.cs
  src/AppModel/NetDaemon.AppModel/Internal/Config/ConfigurationBinder.cs
  src/AppModel/NetDaemon.AppModel/Internal/Config/ConfigurationBinding.cs
  src/AppModel/NetDaemon.AppModel/Internal/Config/IConfigurationBinding.cs
  src/AppModel/NetDaemon.AppModel/Internal/Config/ParameterDefaultValue.cs
Labels: pr: enhancement

#1146 Lazy deserialization of StateChanges
  src/HassModel/NetDaemon.HassModel.Tests/Internal/EntityStateCacheTest.cs
  src/HassModel/NetDeamon.HassModel/Entities/EntityState.cs
  src/HassModel/NetDeamon.HassModel/Entities/StateChange.cs
  src/HassModel/NetDeamon.HassModel/Internal/AppScopedHaContextProvider.cs
  src/HassModel/NetDeamon.HassModel/Internal/EntityStateCache.cs
  src/Runtime/NetDaemon.Runtime/Internal/AppStateManager.cs
Labels: pr: enhancement
