Repository net-daemon/netdaemon, pull requests merged in 2024-02, with the labels that each got.

#1044 MQTT: Advanced example to create a device with five sensors
  src/debug/DebugHost/apps/Extensions/MqttEntityManagerApp.cs
Labels: pr: enhancement

#1053 Upgrade nuget packages
  README.md
  src/AppModel/NetDaemon.AppModel.SourceDeployedApps/NetDaemon.AppModel.SourceDeployedApps.csproj
  src/AppModel/NetDaemon.AppModel.Tests/NetDaemon.AppModel.Tests.csproj
  src/AppModel/NetDaemon.AppModel/NetDaemon.AppModel.csproj
  src/Client/NetDaemon.HassClient.Debug/NetDaemon.HassClient.Debug.csproj
  src/Client/NetDaemon.HassClient.Tests/NetDaemon.HassClient.Tests.csproj
  src/Client/NetDaemon.HassClient/NetDaemon.Client.csproj
  src/Extensions/NetDaemon.Extensions.Logging/NetDaemon.Extensions.Logging.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/NetDaemon.Extensions.Scheduling.Tests.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling/NetDaemon.Extensions.Scheduling.csproj
  src/Extensions/NetDaemon.Extensions.Tts/NetDaemon.Extensions.Tts.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/Host/NetDaemon.Host.Default/NetDaemon.Host.Default.csproj
  src/Runtime/NetDaemon.Runtime.Tests/NetDaemon.Runtime.Tests.csproj
  src/Runtime/NetDaemon.Runtime/NetDaemon.Runtime.csproj
  tests/Integration/NetDaemon.Tests.Integration/NetDaemon.Tests.Integration.csproj
Labels: pr: dependency-update

#1058 Fix a bug wher connection could get stuck infinite time
  src/Runtime/NetDaemon.Runtime/Internal/NetDaemonRuntime.cs
Labels: pr: bugfix

#1059 Add codecov config yaml file
  .github/workflows/ci_build.yml
  codecov.yaml
Labels: pr: enhancement

#1060 Upgrade nuget packages
  README.md
  src/AppModel/NetDaemon.AppModel.SourceDeployedApps/NetDaemon.AppModel.SourceDeployedApps.csproj
  src/AppModel/NetDaemon.AppModel.Tests/NetDaemon.AppModel.Tests.csproj
  src/AppModel/NetDaemon.AppModel/NetDaemon.AppModel.csproj
  src/Client/NetDaemon.HassClient.Debug/NetDaemon.HassClient.Debug.csproj
  src/Client/NetDaemon.HassClient.Tests/NetDaemon.HassClient.Tests.csproj
  src/Client/NetDaemon.HassClient/NetDaemon.Client.csproj
  src/Extensions/NetDaemon.Extensions.Logging/NetDaemon.Extensions.Logging.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/NetDaemon.Extensions.Scheduling.Tests.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling/NetDaemon.Extensions.Scheduling.csproj
  src/Extensions/NetDaemon.Extensions.Tts/NetDaemon.Extensions.Tts.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/Host/NetDaemon.Host.Default/NetDaemon.Host.Default.csproj
  src/Runtime/NetDaemon.Runtime.Tests/NetDaemon.Runtime.Tests.csproj
  src/Runtime/NetDaemon.Runtime/NetDaemon.Runtime.csproj
  tests/Integration/NetDaemon.Tests.Integration/NetDaemon.Tests.Integration.csproj
Labels: pr: dependency-update

#1061 Clean up of error loggings on connection failures and HA disconnects
  src/Client/NetDaemon.HassClient/Internal/HomeAssistantRunner.cs
  src/Host/NetDaemon.Host.Default/Program.cs
Labels: pr: enhancement

#1064 Upgrade latest NuGet packages
  src/AppModel/NetDaemon.AppModel.SourceDeployedApps/NetDaemon.AppModel.SourceDeployedApps.csproj
  src/AppModel/NetDaemon.AppModel/NetDaemon.AppModel.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling/NetDaemon.Extensions.Scheduling.csproj
Labels: pr: dependency-update
