Repository net-daemon/netdaemon, pull requests merged in 2024-08, with the labels that each got.

#1148 Fixed class typo to MqttEntitySubscriptionApp
  src/debug/DebugHost/apps/Extensions/MqttEntitySubscriptionApp.cs
Labels: pr: enhancement

#1149 Improved types for generated service arguments
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ServicesMetaData/HassServiceArgumentMapper.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/ServiceMetaDataParserTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/ServiceMetaDataSamples/calendar.json
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/ServiceMetaDataSamples/light.json
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/ServicesGeneratorTest.cs
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
Labels: pr: enhancement, pr: breaking change

#1155 Upgrade Nuget packages
  src/AppModel/NetDaemon.AppModel.SourceDeployedApps/NetDaemon.AppModel.SourceDeployedApps.csproj
  src/AppModel/NetDaemon.AppModel.Tests/NetDaemon.AppModel.Tests.csproj
  src/Client/NetDaemon.HassClient.Tests/NetDaemon.HassClient.Tests.csproj
  src/Extensions/NetDaemon.Extensions.Logging/NetDaemon.Extensions.Logging.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/NetDaemon.Extensions.Scheduling.Tests.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/Runtime/NetDaemon.Runtime.Tests/NetDaemon.Runtime.Tests.csproj
  tests/Integration/NetDaemon.Tests.Integration/NetDaemon.Tests.Integration.csproj
Labels: pr: dependency-update

#1159 Use lazy for state value in StateChange
  src/HassModel/NetDaemon.HassModel.Tests/Entities/EntityTest.cs
  src/HassModel/NetDeamon.HassModel/Entities/StateChange.cs
Labels: pr: bugfix

#1160 Fix: Registry update fails when Device Model property is an array
  src/Client/NetDaemon.HassClient.Tests/Json/EnsureStringConverterTests.cs
  src/Client/NetDaemon.HassClient/Common/HomeAssistant/Model/HassDevice.cs
  src/Client/NetDaemon.HassClient/Internal/Json/EnsureStringConverter.cs
  src/Client/NetDaemon.HassClient/Internal/Json/ReadNumberAsStringConverter.cs
Labels: pr: bugfix

#1161 Increase queue size of QueuedObservable
  src/HassModel/NetDeamon.HassModel/Internal/QueuedObservable.cs
Labels: pr: enhancement

#1162 Make multiple text selector generate IEnumerable<string>
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ServicesMetaData/SelectorConverter.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/ServicesGeneratorTest.cs
Labels: pr: bugfix
