Repository net-daemon/netdaemon, pull requests merged in 2025-04, with the labels that each got.

#1286 Fixed typos in NetDaemon.
  src/Runtime/NetDaemon.Runtime/Common/Extensions/HostBuilderExtensions.cs
  tests/Integration/NetDaemon.Tests.Integration/Helpers/NetDaemonIntegrationBase.cs
Labels: pr: enhancement

#1287 Updating readme.
  README.md
Labels: pr: enhancement

#1290 Doc/fix readme example
  README.md
Labels: pr: enhancement

#1299 fix #1288 Codegen parameter name conflict when a field is called 'tar…
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/ExtensionMethodsGenerator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/ServiceArguments.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/CodeGeneration/ServicesGenerator.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/ServicesGeneratorTest.cs
Labels: pr: bugfix

#1300 Upgrade nuget packages
  src/AppModel/NetDaemon.AppModel.SourceDeployedApps/NetDaemon.AppModel.SourceDeployedApps.csproj
  src/AppModel/NetDaemon.AppModel.Tests/NetDaemon.AppModel.Tests.csproj
  src/AppModel/NetDaemon.AppModel/NetDaemon.AppModel.csproj
  src/Client/NetDaemon.HassClient.Debug/NetDaemon.HassClient.Debug.csproj
  src/Client/NetDaemon.HassClient.Tests/NetDaemon.HassClient.Tests.csproj
  src/Client/NetDaemon.HassClient/NetDaemon.Client.csproj
  src/Extensions/NetDaemon.Extensions.Logging/NetDaemon.Extensions.Logging.csproj
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/NetDaemon.Extensions.MqttEntityManager.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/NetDaemon.Extensions.Scheduling.Tests.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling/NetDaemon.Extensions.Scheduling.csproj
  src/Extensions/NetDaemon.Extensions.Tts/NetDaemon.Extensions.Tts.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/HassModel/NetDaemon.HassModel/NetDaemon.HassModel.csproj
  src/Host/NetDaemon.Host.Default/NetDaemon.Host.Default.csproj
  src/Runtime/NetDaemon.Runtime.Tests/NetDaemon.Runtime.Tests.csproj
  src/Runtime/NetDaemon.Runtime/NetDaemon.Runtime.csproj
  tests/Integration/NetDaemon.Tests.Integration/NetDaemon.Tests.Integration.csproj
Labels: pr: dependency-update

#1301 Fix 1278: CodeGen, Remove unused properties from selector types to avoid deserialization errors
  src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ServicesMetaData/Selectors.cs
Labels: pr: bugfix

#1304 Copy identifiers from homeassistant device_registry
  src/Client/NetDaemon.HassClient.Tests/Json/HassDeviceConverterTests.cs
  src/Client/NetDaemon.HassClient/Common/HomeAssistant/Model/HassDevice.cs
  src/HassModel/NetDaemon.HassModel.Tests/Internal/HassObjectMapperTest.cs
  src/HassModel/NetDaemon.HassModel/Internal/HassObjectMapper.cs
  src/HassModel/NetDaemon.HassModel/Registry/Device.cs
Labels: pr: new-feature
