Repository net-daemon/netdaemon, pull requests merged in 2025-02, with the labels that each got.

#1250 Include NameByUser in HassModel
  src/HassModel/NetDeamon.HassModel/Internal/HassObjectMapper.cs
  src/HassModel/NetDeamon.HassModel/Registry/Device.cs
Labels: pr: enhancement

#1247 Feature/state changes with current
  src/HassModel/NetDaemon.HassModel.Tests/Entities/EntityExtensions.CallServiceWithResponseAsync.Test.cs
  src/HassModel/NetDaemon.HassModel.Tests/Entities/EntityExtensions.OnOff.Test.cs
  src/HassModel/NetDaemon.HassModel.Tests/Entities/EntityExtensions.WithCurrent.ConcreteEntity.Test.cs
  src/HassModel/NetDaemon.HassModel.Tests/Entities/EntityExtensions.WithCurrent.Entity.Test.cs
  src/HassModel/NetDaemon.HassModel.Tests/Entities/EntityExtensionsTest.cs
  src/HassModel/NetDeamon.HassModel/Entities/EntityExtensions.cs
Labels: pr: new-feature

#1251 Strongly-type EntityState.Attributes
  src/HassModel/NetDeamon.HassModel/Entities/Entity.cs
  src/HassModel/NetDeamon.HassModel/Entities/EntityState.cs
Labels: pr: enhancement

#1262 Fix hass model foldername
  NetDaemon.sln
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDaemon.HassModel.Integration/NetDaemon.HassModel.Integration.csproj
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/HassModel/NetDaemon.HassModel/Context.cs
  src/HassModel/NetDaemon.HassModel/DependencyInjectionSetup.cs
  src/HassModel/NetDaemon.HassModel/Entities/Core/CoreInterfaces.cs
  src/HassModel/NetDaemon.HassModel/Entities/Core/IEntityCore.cs
  src/HassModel/NetDaemon.HassModel/Entities/Core/LightAttributesBase.cs
  src/HassModel/NetDaemon.HassModel/Entities/Core/MediaPlayerAttributesBase.cs
  src/HassModel/NetDaemon.HassModel/Entities/DefaultEntityFactory.cs
  src/HassModel/NetDaemon.HassModel/Entities/Entity.cs
  src/HassModel/NetDaemon.HassModel/Entities/EntityExtensions.cs
  src/HassModel/NetDaemon.HassModel/Entities/EntityState.cs
  src/HassModel/NetDaemon.HassModel/Entities/EnumerableEntityExtensions.cs
  src/HassModel/NetDaemon.HassModel/Entities/NumericEntity.cs
  src/HassModel/NetDaemon.HassModel/Entities/NumericEntityState.cs
  src/HassModel/NetDaemon.HassModel/Entities/StateChange.cs
  src/HassModel/NetDaemon.HassModel/Event.cs
  src/HassModel/NetDaemon.HassModel/GlobalUsings.cs
  src/HassModel/NetDaemon.HassModel/HaContextExtensions.cs
  src/HassModel/NetDaemon.HassModel/HaRegistry.cs
  src/HassModel/NetDaemon.HassModel/ICacheManager.cs
  src/HassModel/NetDaemon.HassModel/IEntityFactory.cs
  src/HassModel/NetDaemon.HassModel/IHaContext.cs
  src/HassModel/NetDaemon.HassModel/IHaRegistry.cs
  src/HassModel/NetDaemon.HassModel/IHaRegistryNavigator.cs
  src/HassModel/NetDaemon.HassModel/ITriggerManager.cs
  src/HassModel/NetDaemon.HassModel/Internal/AppScopedHaContextProvider.cs
  src/HassModel/NetDaemon.HassModel/Internal/BackgroundTaskTracker.cs
  src/HassModel/NetDaemon.HassModel/Internal/CacheManager.cs
  src/HassModel/NetDaemon.HassModel/Internal/EntityStateCache.cs
  src/HassModel/NetDaemon.HassModel/Internal/ExtensionMethods.cs
  src/HassModel/NetDaemon.HassModel/Internal/FormatHelpers.cs
  src/HassModel/NetDaemon.HassModel/Internal/HassObjectMapper.cs
  src/HassModel/NetDaemon.HassModel/Internal/IBackgroundTaskTracker.cs
  src/HassModel/NetDaemon.HassModel/Internal/QueuedObservable.cs
  src/HassModel/NetDaemon.HassModel/Internal/RegistryCache.cs
  src/HassModel/NetDaemon.HassModel/Internal/ScopedObservable.cs
  src/HassModel/NetDaemon.HassModel/Internal/TriggerManager.cs
  src/HassModel/NetDaemon.HassModel/NetDaemon.HassModel.csproj
  src/HassModel/NetDaemon.HassModel/ObservableExtensions.cs
  src/HassModel/NetDaemon.HassModel/Registry/Area.cs
  src/HassModel/NetDaemon.HassModel/Registry/ConversationOptions.cs
  src/HassModel/NetDaemon.HassModel/Registry/Device.cs
  src/HassModel/NetDaemon.HassModel/Registry/EntityOptions.cs
  src/HassModel/NetDaemon.HassModel/Registry/EntityRegistration.cs
  src/HassModel/NetDaemon.HassModel/Registry/Floor.cs
  src/HassModel/NetDaemon.HassModel/Registry/Label.cs
  src/HassModel/NetDaemon.HassModel/ServiceTarget.cs
  src/HassModel/NetDaemon.HassModel/StateObservableExtensions.cs
  src/HassModel/NetDaemon.HassModel/TriggerManagerExtensions.cs
  src/Runtime/NetDaemon.Runtime/NetDaemon.Runtime.csproj
  src/debug/DebugHost/DebugHost.csproj
  src/debug/DebugWebHost/DebugWebHost.csproj
  src/debug/MyLibrary/MyLibrary.csproj
  src/debug/MyNDApp/MyNDApp.csproj
Labels: pr: enhancement

#1263 remove ''**/core' from .gitignore
  .gitignore
Labels: pr: enhancement

#1265 Upgrade nuget packages
  src/AppModel/NetDaemon.AppModel.SourceDeployedApps/NetDaemon.AppModel.SourceDeployedApps.csproj
  src/AppModel/NetDaemon.AppModel.Tests/NetDaemon.AppModel.Tests.csproj
  src/AppModel/NetDaemon.AppModel/NetDaemon.AppModel.csproj
  src/Client/NetDaemon.HassClient.Debug/NetDaemon.HassClient.Debug.csproj
  src/Client/NetDaemon.HassClient.Tests/NetDaemon.HassClient.Tests.csproj
  src/Client/NetDaemon.HassClient/NetDaemon.Client.csproj
  src/Extensions/NetDaemon.Extensions.Logging/NetDaemon.Extensions.Logging.csproj
  src/Extensions/NetDaemon.Extensions.MqttEntityManager/NetDaemon.Extensions.MqttEntityManager.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling.Tests/NetDaemon.Extensions.Scheduling.Tests.csproj
  src/Extensions/NetDaemon.Extensions.Scheduling/NetDaemon.Extensions.Scheduling.csproj
  src/Extensions/NetDaemon.Extensions.Tts/NetDaemon.Extensions.Tts.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
  src/HassModel/NetDaemon.HassModel/NetDaemon.HassModel.csproj
  src/Host/NetDaemon.Host.Default/NetDaemon.Host.Default.csproj
  src/Runtime/NetDaemon.Runtime.Tests/NetDaemon.Runtime.Tests.csproj
  src/Runtime/NetDaemon.Runtime/NetDaemon.Runtime.csproj
  tests/Integration/NetDaemon.Tests.Integration/NetDaemon.Tests.Integration.csproj
Labels: pr: dependency-update

#1266 Use MSBuild to load projects, instead of manual parsing
  .gitignore
  src/HassModel/NetDaemon.HassModel.CodeGenerator/DependencyValidator.cs
  src/HassModel/NetDaemon.HassModel.CodeGenerator/NetDaemon.HassModel.CodeGenerator.csproj
  src/HassModel/NetDaemon.HassModel.CodeGenerator/Program.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/DependencyValidatorTests.cs
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/TestFiles/RawVersions/RawVersions.csproj
  src/HassModel/NetDaemon.HassModel.Tests/CodeGenerator/TestFiles/SubstitutedVersions/SubstitutedVersions.csproj
  src/HassModel/NetDaemon.HassModel.Tests/NetDaemon.HassModel.Tests.csproj
Labels: pr: enhancement
